package io.agenticai.chk.entity;

import io.agenticai.chk.domain.ActiveCheckStatus;
import io.agenticai.chk.entity.converter.ActiveCheckStatusConverter;
import jakarta.persistence.Column;
import jakarta.persistence.Convert;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

import java.time.OffsetDateTime;
import java.util.Objects;

/**
 * ENT-CHK-001 Active Check — one row of {@code CHK_ACTIVE_CHECK} per unfinished Check: its status
 * and the deadline that ends it (REQ-CHK-076, ADR-CHK-015). Kind {@code transactional}: carries
 * the standard {@code createdAt} / {@code updatedAt} fields. PRIVATE to CHK; its one read view is
 * API-CHK-001 (checkId, checkStatus, deadlineAt — never the key or the audit fields, ADR-CHK-017).
 *
 * <p>Life cycle (STATE MACHINE of DATA-DOM): created by {@link #started} with status
 * {@code AWAITING_DOCUMENTS} ({@code manual} service) or {@code RUNNING} ({@code path} /
 * {@code blob}); the only transition is {@code AWAITING_DOCUMENTS → RUNNING} on confirmation,
 * executed by {@link #confirmUploads} (REQ-CHK-077); hard-deleted when the Check ends COMPLETED or
 * FAILED (REQ-CHK-078) — the deletion is the one place that decides which ending path wins
 * (REQ-CHK-079, ADR-CHK-015) and is written inline in the SVC-API procedures (ADR-CHK-017). No
 * setter exists.
 *
 * <p>Holds only the Check's identifier, its status and its deadline (REQ-CHK-082, guardrail G9) —
 * no request data, result or document content. The Check identifier is a VALUE returned by the
 * result port — no foreign key, no read of RPT (ADR-CHK-016).
 *
 * <p>Rules: RULE-CHK-008 (one Active Check per Check, owner layer repository) is
 * {@code UQ_CHK_ACTIVE_CHECK_CHECK_ID}, its duplicate-key violation handled by the start
 * procedure. RULE-CHK-009 (only an unfinished status, owner layer domain) is structural: the
 * closed {@link ActiveCheckStatus} enum makes COMPLETED / FAILED unrepresentable, the
 * {@link ActiveCheckStatusConverter} refuses any other stored value and
 * {@code CHK_CHK_ACTIVE_CHECK_CHECK_STATUS} backstops it — nothing is left to decide at runtime, so
 * no separate domain class exists for it. RULE-CHK-010 (confirmation only while
 * AWAITING_DOCUMENTS, code {@code CHK-409-CHECK-NOT-AWAITING-DOCUMENTS}) is the service's
 * (CheckConfirmationService, under its {@code SELECT … FOR UPDATE}).
 */
@Entity
@Table(name = "CHK_ACTIVE_CHECK",
        uniqueConstraints = {
                @UniqueConstraint(name = "UQ_CHK_ACTIVE_CHECK_CHECK_ID", columnNames = {"CHECK_ID"})
        },
        indexes = {
                @Index(name = "IDX_CHK_ACTIVE_CHECK_DEADLINE_AT", columnList = "DEADLINE_AT")
        })
public class ActiveCheck {

    /** DBF-CHK-001 — identity key, {@code NUMBER(19) GENERATED BY DEFAULT AS IDENTITY}. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ACTIVE_CHECK_ID", nullable = false, updatable = false)
    private Long activeCheckId;

    /**
     * DBF-CHK-002 — the identifier of the Check returned by the result port (REQ-CHK-076,
     * REQ-CHK-078, REQ-CHK-079), set once; unique ({@code UQ_CHK_ACTIVE_CHECK_CHECK_ID},
     * RULE-CHK-008), which also serves the locking read, the update and the delete by Check. A
     * value, never a foreign key (ADR-CHK-016).
     */
    @Column(name = "CHECK_ID", nullable = false, updatable = false)
    private Long checkId;

    /**
     * DBF-CHK-003 — {@code AWAITING_DOCUMENTS} or {@code RUNNING} only (REQ-CHK-076, REQ-CHK-077,
     * RULE-CHK-009; {@code CHK_CHK_ACTIVE_CHECK_CHECK_STATUS}). Changes only through
     * {@link #confirmUploads}.
     */
    @Convert(converter = ActiveCheckStatusConverter.class)
    @Column(name = "CHECK_STATUS", length = 30, nullable = false)
    private ActiveCheckStatus checkStatus;

    /**
     * DBF-CHK-004 — the end of the upload window while {@code AWAITING_DOCUMENTS}, the end of the
     * Check timeout while {@code RUNNING} (REQ-CHK-076, REQ-CHK-077, REQ-CHK-080); indexed by
     * {@code IDX_CHK_ACTIVE_CHECK_DEADLINE_AT} for the deadline check. Computed by the service
     * from {@code aias.check.upload-window} / {@code aias.check.timeout} — never a constant here.
     */
    @Column(name = "DEADLINE_AT", nullable = false)
    private OffsetDateTime deadlineAt;

    /**
     * DBF-CHK-005 — standard field ({@code entity_defaults.transactional}, REQ-CHK-076): the start
     * time, filled by the database ({@code DEFAULT SYSTIMESTAMP}, no trigger) — mapped read-only,
     * never set from code or request data.
     */
    @Column(name = "CREATED_AT", nullable = false, insertable = false, updatable = false)
    private OffsetDateTime createdAt;

    /**
     * DBF-CHK-006 — standard field ({@code entity_defaults.transactional}, REQ-CHK-077), filled by
     * the database ({@code DEFAULT SYSTIMESTAMP}, no trigger) — mapped read-only. On confirmation
     * the SVC-API procedure's own UPDATE sets {@code UPDATED_AT = SYSTIMESTAMP}; this mapping never
     * writes it.
     */
    @Column(name = "UPDATED_AT", nullable = false, insertable = false, updatable = false)
    private OffsetDateTime updatedAt;

    /** JPA only. */
    protected ActiveCheck() {
    }

    private ActiveCheck(Long checkId, ActiveCheckStatus checkStatus, OffsetDateTime deadlineAt) {
        this.checkId = checkId;
        this.checkStatus = checkStatus;
        this.deadlineAt = deadlineAt;
    }

    /**
     * An Active Check as the start of a Check records it (REQ-CHK-076, AC-CHK-079) — this method
     * stores, it does not decide. The initial status follows the service's fetch mode and the
     * deadline is computed by the start procedure; the {@link ActiveCheckStatus} type itself is
     * RULE-CHK-009. One Active Check per Check (RULE-CHK-008) is the unique constraint's.
     *
     * @param checkId       the Check identifier returned by the result port (a value, never a key)
     * @param initialStatus {@code AWAITING_DOCUMENTS} for a {@code manual} service, otherwise
     *                      {@code RUNNING}
     * @param deadlineAt    the end of the upload window or of the Check timeout
     */
    public static ActiveCheck started(Long checkId,
                                      ActiveCheckStatus initialStatus,
                                      OffsetDateTime deadlineAt) {
        Objects.requireNonNull(checkId, "checkId");
        Objects.requireNonNull(initialStatus, "initialStatus");
        Objects.requireNonNull(deadlineAt, "deadlineAt");
        return new ActiveCheck(checkId, initialStatus, deadlineAt);
    }

    /**
     * Executes the one transition, {@code AWAITING_DOCUMENTS → RUNNING}, with the deadline at the
     * end of the Check timeout counted from the confirmation (REQ-CHK-077, AC-CHK-080). Whether
     * the confirmation is allowed is RULE-CHK-010, decided by the confirmation service under its
     * locking read before this call (code {@code CHK-409-CHECK-NOT-AWAITING-DOCUMENTS}); a call on
     * an Active Check that is not {@code AWAITING_DOCUMENTS} can only be a programming error.
     *
     * @param runningDeadline the end of the Check timeout, counted from the confirmation
     * @throws IllegalStateException when the Active Check is not {@code AWAITING_DOCUMENTS}
     *         (misuse, internal only — never an HTTP error)
     */
    public void confirmUploads(OffsetDateTime runningDeadline) {
        Objects.requireNonNull(runningDeadline, "runningDeadline");
        if (checkStatus != ActiveCheckStatus.AWAITING_DOCUMENTS) {
            throw new IllegalStateException("Active Check of Check " + checkId
                    + " is " + checkStatus + ", not AWAITING_DOCUMENTS; confirmUploads called without RULE-CHK-010");
        }
        this.checkStatus = ActiveCheckStatus.RUNNING;
        this.deadlineAt = runningDeadline;
    }

    public Long getActiveCheckId() {
        return activeCheckId;
    }

    public Long getCheckId() {
        return checkId;
    }

    public ActiveCheckStatus getCheckStatus() {
        return checkStatus;
    }

    public OffsetDateTime getDeadlineAt() {
        return deadlineAt;
    }

    /** Database-filled; {@code null} on an instance not yet reloaded after its insert. */
    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    /** Database-filled; {@code null} on an instance not yet reloaded after its insert. */
    public OffsetDateTime getUpdatedAt() {
        return updatedAt;
    }
}
