package io.agenticai.reg.entity;

import io.agenticai.reg.domain.ConnectionType;
import io.agenticai.reg.entity.converter.ConnectionTypeConverter;
import jakarta.persistence.Column;
import jakarta.persistence.Convert;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

import java.time.OffsetDateTime;
import java.util.Objects;

/**
 * ENT-REG-005 Connection — one row of {@code REG_CONNECTION} per named, read-only data source of
 * this environment (REQ-REG-046). Kind {@code config}: no audit columns.
 *
 * <p>Written only by the activation step of the load run (ADR-REG-009): a connection is
 * registered through {@link #fromActivation}, updated in place by a later activation through
 * {@link #updateFromActivation} (its name is the business key and never changes), and removed by hard
 * delete when the activation configuration no longer lists it. Every rule of this entity
 * (RULE-REG-013, 014, 015, 025, 027) is owned by the service layer; the database backstops are
 * {@code UQ_REG_CONNECTION_CONNECTION_NAME} and the {@code CHK_REG_CONNECTION_*} constraints.
 *
 * <p>Holds a credential <em>reference</em> only — never the credential (REQ-REG-054,
 * ADR-REG-009) — and no request data (REQ-REG-059).
 */
@Entity
@Table(name = "REG_CONNECTION",
        uniqueConstraints = {
                @UniqueConstraint(name = "UQ_REG_CONNECTION_CONNECTION_NAME", columnNames = {"CONNECTION_NAME"})
        })
public class Connection {

    /** DBF-REG-029 — identity key, {@code NUMBER(19) GENERATED BY DEFAULT AS IDENTITY}. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "CONNECTION_ID", nullable = false, updatable = false)
    private Long connectionId;

    /**
     * DBF-REG-030 — the connection name, unique per environment and immutable (REQ-REG-046 …
     * REQ-REG-048, REQ-REG-073, RULE-REG-013).
     */
    @Column(name = "CONNECTION_NAME", length = 100, nullable = false, updatable = false)
    private String connectionName;

    /**
     * DBF-REG-031 — {@code mcp | jdbc} (REQ-REG-052, REQ-REG-040, REQ-REG-072, RULE-REG-014,
     * RULE-REG-025), stored through {@link ConnectionTypeConverter}
     * ({@code CHK_REG_CONNECTION_CONNECTION_TYPE}).
     */
    @Convert(converter = ConnectionTypeConverter.class)
    @Column(name = "CONNECTION_TYPE", length = 10, nullable = false)
    private ConnectionType connectionType;

    /** DBF-REG-032 — the MCP server address or JDBC URL (REQ-REG-049, REQ-REG-050, REQ-REG-073). */
    @Column(name = "ENDPOINT", length = 500, nullable = false)
    private String endpoint;

    /**
     * DBF-REG-033 — the MCP query tool name; required for {@code mcp} (REQ-REG-048,
     * {@code CHK_REG_CONNECTION_QUERY_TOOL}).
     */
    @Column(name = "QUERY_TOOL", length = 100)
    private String queryTool;

    /** DBF-REG-034 — the SQL dialect of the data source (REQ-REG-048). */
    @Column(name = "DIALECT", length = 30, nullable = false)
    private String dialect;

    /**
     * DBF-REG-035 — the name of the credential in the environment's secret store — never the
     * secret (REQ-REG-054).
     */
    @Column(name = "CREDENTIAL_REFERENCE", length = 200, nullable = false)
    private String credentialReference;

    /**
     * DBF-REG-036 — the administrator's read-only declaration; must be {@code 1} (REQ-REG-055,
     * RULE-REG-015, {@code CHK_REG_CONNECTION_READ_ONLY}).
     */
    @Column(name = "READ_ONLY", nullable = false)
    private Boolean readOnly;

    /**
     * DBF-REG-037 — {@code 1} = the database user is limited to specific views (REQ-REG-056);
     * database default {@code 0}, {@code CHK_REG_CONNECTION_LIMITED_TO_VIEWS}.
     */
    @Column(name = "LIMITED_TO_VIEWS", nullable = false)
    private Boolean limitedToViews;

    /** DBF-REG-038 — the environment that activated the connection (REQ-REG-049). */
    @Column(name = "ENVIRONMENT_NAME", length = 50, nullable = false)
    private String environmentName;

    /** DBF-REG-039 — the last activation that registered or updated the connection (REQ-REG-049, REQ-REG-050). */
    @Column(name = "ACTIVATED_AT", nullable = false)
    private OffsetDateTime activatedAt;

    /** JPA only. */
    protected Connection() {
    }

    private Connection(String connectionName) {
        this.connectionName = connectionName;
    }

    /**
     * A connection as the activation step registers it (REQ-REG-049), after every activation
     * rule has accepted it — this method stores, it does not decide.
     *
     * @param connectionName      the declared connection name
     * @param connectionType      the declared type
     * @param endpoint            the declared endpoint
     * @param queryTool           the declared query tool, or {@code null} for a {@code jdbc} connection
     * @param dialect             the declared SQL dialect
     * @param credentialReference the credential reference — never the credential
     * @param readOnly            the read-only declaration (already accepted by RULE-REG-015)
     * @param limitedToViews      whether the user is limited to specific views
     * @param environmentName     the environment activating the connection
     * @param activatedAt         the time of the activation
     */
    public static Connection fromActivation(String connectionName,
                                       ConnectionType connectionType,
                                       String endpoint,
                                       String queryTool,
                                       String dialect,
                                       String credentialReference,
                                       boolean readOnly,
                                       boolean limitedToViews,
                                       String environmentName,
                                       OffsetDateTime activatedAt) {
        Objects.requireNonNull(connectionName, "connectionName");
        Connection connection = new Connection(connectionName);
        connection.updateFromActivation(connectionType, endpoint, queryTool, dialect, credentialReference,
                readOnly, limitedToViews, environmentName, activatedAt);
        return connection;
    }

    /**
     * Updates the connection from a later activation (REQ-REG-050): every declared value except
     * the name is replaced and {@code activatedAt} moves to this activation. Called only after
     * the activation rules (RULE-REG-014, RULE-REG-015, RULE-REG-025) have accepted the new
     * values — this method stores, it does not decide.
     */
    public void updateFromActivation(ConnectionType connectionType,
                           String endpoint,
                           String queryTool,
                           String dialect,
                           String credentialReference,
                           boolean readOnly,
                           boolean limitedToViews,
                           String environmentName,
                           OffsetDateTime activatedAt) {
        this.connectionType = Objects.requireNonNull(connectionType, "connectionType");
        this.endpoint = Objects.requireNonNull(endpoint, "endpoint");
        this.queryTool = queryTool;
        this.dialect = Objects.requireNonNull(dialect, "dialect");
        this.credentialReference = Objects.requireNonNull(credentialReference, "credentialReference");
        this.readOnly = readOnly;
        this.limitedToViews = limitedToViews;
        this.environmentName = Objects.requireNonNull(environmentName, "environmentName");
        this.activatedAt = Objects.requireNonNull(activatedAt, "activatedAt");
    }

    public Long getConnectionId() {
        return connectionId;
    }

    public String getConnectionName() {
        return connectionName;
    }

    public ConnectionType getConnectionType() {
        return connectionType;
    }

    public String getEndpoint() {
        return endpoint;
    }

    /** {@code null} for a {@code jdbc} connection. */
    public String getQueryTool() {
        return queryTool;
    }

    public String getDialect() {
        return dialect;
    }

    public String getCredentialReference() {
        return credentialReference;
    }

    public boolean isReadOnly() {
        return Boolean.TRUE.equals(readOnly);
    }

    public boolean isLimitedToViews() {
        return Boolean.TRUE.equals(limitedToViews);
    }

    public String getEnvironmentName() {
        return environmentName;
    }

    public OffsetDateTime getActivatedAt() {
        return activatedAt;
    }
}
