package io.agenticai.reg.entity;

import io.agenticai.reg.domain.LoadOutcome;
import io.agenticai.reg.domain.LoadSubject;
import io.agenticai.reg.entity.converter.LoadOutcomeConverter;
import io.agenticai.reg.entity.converter.LoadSubjectConverter;
import jakarta.persistence.Column;
import jakarta.persistence.Convert;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;

import java.time.OffsetDateTime;
import java.util.Objects;

/**
 * ENT-REG-006 Load Result — one row of {@code REG_LOAD_RESULT} per outcome of a load run: the
 * load report (REQ-REG-007, REQ-REG-008). Kind {@code transactional}: carries the standard
 * {@code createdAt} / {@code updatedAt} fields.
 *
 * <p>Immutable once stored: a Load Result is created by the load run (ADR-REG-007), read as the
 * load report (QR-REG-005, API-REG-003) and deleted by the next load run — it is never updated —
 * so this class has no setter at all; every column is {@code updatable = false} and the only way
 * in is {@link #recorded}. The whole run is one transaction under one exclusive lock on this
 * table (REQ-REG-067, ADR-REG-015) — the lock is the load run's concern, not this mapping's.
 *
 * <p>The rules of this entity are owned by the service layer (load run): RULE-REG-023 (the
 * package directory is reachable — else one {@code PACKAGE_DIRECTORY} row, REQ-REG-066,
 * ADR-REG-018) and RULE-REG-028 (subject name, service code and reason are shortened by the
 * single writer through {@code LoadResultText.fit} before every insert, REQ-REG-074,
 * ADR-REG-022). The database backstops are {@code CHK_REG_LOAD_RESULT_SUBJECT_KIND},
 * {@code CHK_REG_LOAD_RESULT_OUTCOME} and {@code CHK_REG_LOAD_RESULT_REASON} (reason required
 * when {@code REJECTED}). This table has no foreign key and no unique constraint.
 * No request data is held (REQ-REG-059): folder / connection names, codes, versions and rule
 * messages only.
 */
@Entity
@Table(name = "REG_LOAD_RESULT",
        indexes = {
                @Index(name = "IDX_REG_LOAD_RESULT_LOAD_RUN_AT", columnList = "LOAD_RUN_AT")
        })
public class LoadResult {

    /** DBF-REG-040 — identity key, {@code NUMBER(19) GENERATED BY DEFAULT AS IDENTITY}. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "LOAD_RESULT_ID", nullable = false, updatable = false)
    private Long loadResultId;

    /**
     * DBF-REG-041 — the start of the load run that recorded this outcome (REQ-REG-008,
     * REQ-REG-009, REQ-REG-067, REQ-REG-068); every row of one run carries the same value, and
     * the load report is the rows of the latest one ({@code IDX_REG_LOAD_RESULT_LOAD_RUN_AT}).
     */
    @Column(name = "LOAD_RUN_AT", nullable = false, updatable = false)
    private OffsetDateTime loadRunAt;

    /**
     * DBF-REG-042 — what the row is about (REQ-REG-008, REQ-REG-066), stored as
     * {@code SERVICE_PACKAGE | CONNECTION | PACKAGE_DIRECTORY} through
     * {@link LoadSubjectConverter} ({@code CHK_REG_LOAD_RESULT_SUBJECT_KIND}, ADR-REG-018).
     */
    @Convert(converter = LoadSubjectConverter.class)
    @Column(name = "SUBJECT_KIND", length = 20, nullable = false, updatable = false)
    private LoadSubject subjectKind;

    /**
     * DBF-REG-043 — the folder name, connection name or package directory path (REQ-REG-008,
     * REQ-REG-066, REQ-REG-073, REQ-REG-074); shortened to 200 characters by the writer
     * (RULE-REG-028). A name, never a foreign key.
     */
    @Column(name = "SUBJECT_NAME", length = 200, nullable = false, updatable = false)
    private String subjectName;

    /**
     * DBF-REG-044 — the service code as the folder declared it (REQ-REG-008, REQ-REG-074);
     * absent when the folder could not be read; shortened to 100 characters by the writer
     * (RULE-REG-028). Open data — a {@code String}, never an enum.
     */
    @Column(name = "SERVICE_CODE", length = 100, updatable = false)
    private String serviceCode;

    /** DBF-REG-045 — the version number as the folder declared it (REQ-REG-008); absent when unknown. */
    @Column(name = "VERSION_NUMBER", updatable = false)
    private Integer versionNumber;

    /**
     * DBF-REG-046 — the outcome (REQ-REG-007, REQ-REG-008), stored as
     * {@code REGISTERED | UNCHANGED | REJECTED | WITHDRAWN | ACTIVATED | UPDATED | REMOVED}
     * through {@link LoadOutcomeConverter} ({@code CHK_REG_LOAD_RESULT_OUTCOME}).
     */
    @Convert(converter = LoadOutcomeConverter.class)
    @Column(name = "OUTCOME", length = 20, nullable = false, updatable = false)
    private LoadOutcome outcome;

    /**
     * DBF-REG-047 — the rule message (REQ-REG-007, REQ-REG-008, REQ-REG-074); required when the
     * outcome is {@code REJECTED} ({@code CHK_REG_LOAD_RESULT_REASON}, decided by the load run);
     * shortened to 1000 characters by the writer (RULE-REG-028).
     */
    @Column(name = "REASON", length = 1000, updatable = false)
    private String reason;

    /**
     * DBF-REG-048 — standard field ({@code entity_defaults.transactional}, REQ-REG-007), filled by
     * the database ({@code DEFAULT SYSTIMESTAMP}, no trigger) — mapped read-only, never set from
     * code or request data.
     */
    @Column(name = "CREATED_AT", nullable = false, insertable = false, updatable = false)
    private OffsetDateTime createdAt;

    /**
     * DBF-REG-049 — standard field ({@code entity_defaults.transactional}, REQ-REG-007), filled by
     * the database ({@code DEFAULT SYSTIMESTAMP}, no trigger) — mapped read-only. A Load Result is
     * never updated, so the insert-time default is its final value.
     */
    @Column(name = "UPDATED_AT", nullable = false, insertable = false, updatable = false)
    private OffsetDateTime updatedAt;

    /** JPA only. */
    protected LoadResult() {
    }

    private LoadResult(OffsetDateTime loadRunAt,
                       LoadSubject subjectKind,
                       String subjectName,
                       String serviceCode,
                       Integer versionNumber,
                       LoadOutcome outcome,
                       String reason) {
        this.loadRunAt = loadRunAt;
        this.subjectKind = subjectKind;
        this.subjectName = subjectName;
        this.serviceCode = serviceCode;
        this.versionNumber = versionNumber;
        this.outcome = outcome;
        this.reason = reason;
    }

    /**
     * An outcome as the load run records it (REQ-REG-007, ADR-REG-007) — this method stores, it
     * does not decide: the required values are checked for presence only, the optional ones are
     * stored as given. Whether a reason is required ({@code REJECTED}) and whether the text fits
     * its column (RULE-REG-028) are the writer's rules, applied before this call; the CHECK
     * constraints backstop them.
     *
     * @param loadRunAt     the start of the load run recording the outcome
     * @param subjectKind   what the row is about
     * @param subjectName   the folder name, connection name or package directory path (already fitted)
     * @param serviceCode   the service code as declared (already fitted), or {@code null} when unreadable
     * @param versionNumber the version number as declared, or {@code null} when unknown
     * @param outcome       the outcome
     * @param reason        the rule message (already fitted), or {@code null} when there is none
     */
    public static LoadResult recorded(OffsetDateTime loadRunAt,
                                      LoadSubject subjectKind,
                                      String subjectName,
                                      String serviceCode,
                                      Integer versionNumber,
                                      LoadOutcome outcome,
                                      String reason) {
        Objects.requireNonNull(loadRunAt, "loadRunAt");
        Objects.requireNonNull(subjectKind, "subjectKind");
        Objects.requireNonNull(subjectName, "subjectName");
        Objects.requireNonNull(outcome, "outcome");
        return new LoadResult(loadRunAt, subjectKind, subjectName, serviceCode, versionNumber,
                outcome, reason);
    }

    public Long getLoadResultId() {
        return loadResultId;
    }

    public OffsetDateTime getLoadRunAt() {
        return loadRunAt;
    }

    public LoadSubject getSubjectKind() {
        return subjectKind;
    }

    public String getSubjectName() {
        return subjectName;
    }

    /** {@code null} when the folder could not be read. */
    public String getServiceCode() {
        return serviceCode;
    }

    /** {@code null} when the version number is unknown. */
    public Integer getVersionNumber() {
        return versionNumber;
    }

    public LoadOutcome getOutcome() {
        return outcome;
    }

    /** {@code null} when there is no rule message; never {@code null} when {@code REJECTED}. */
    public String getReason() {
        return reason;
    }

    /** Database-filled; {@code null} on an instance not yet reloaded after its insert. */
    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    /** Database-filled; {@code null} on an instance not yet reloaded after its insert. */
    public OffsetDateTime getUpdatedAt() {
        return updatedAt;
    }
}
