package io.agenticai.reg.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

import java.util.Objects;

/**
 * ENT-REG-004 Required Document — one row of {@code REG_REQ_DOC} per document type a stored
 * version requires (REQ-REG-037). Kind {@code config}: no audit columns. A version may declare
 * none.
 *
 * <p>Created with its version and never changed (ADR-REG-003): no setters. The owning version is
 * referenced by its id ({@code SERVICE_PACKAGE_VERSION_ID}, {@code FK_REG_REQ_DOC_REG_SVC_PKG_VER}).
 * The document type is open data of the service registry (ADR-REG-010) — a {@code String},
 * never an enum. RULE-REG-021 is owned by the service layer; {@code UQ_REG_REQ_DOC_VER_TYPE} is
 * its backstop. No document content is held (REQ-REG-059).
 */
@Entity
@Table(name = "REG_REQ_DOC",
        uniqueConstraints = {
                @UniqueConstraint(name = "UQ_REG_REQ_DOC_VER_TYPE",
                        columnNames = {"SERVICE_PACKAGE_VERSION_ID", "DOCUMENT_TYPE"})
        },
        indexes = {
                @Index(name = "IDX_REG_REQ_DOC_SERVICE_PACKAGE_VERSION_ID",
                        columnList = "SERVICE_PACKAGE_VERSION_ID, REQUIRED_DOCUMENT_ID")
        })
public class RequiredDocument {

    /** DBF-REG-026 — identity key, {@code NUMBER(19) GENERATED BY DEFAULT AS IDENTITY}. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "REQUIRED_DOCUMENT_ID", nullable = false, updatable = false)
    private Long requiredDocumentId;

    /**
     * DBF-REG-027 — the document type, as the host's document type column returns it; unique
     * per version (REQ-REG-037, REQ-REG-057, REQ-REG-063, RULE-REG-021).
     */
    @Column(name = "DOCUMENT_TYPE", length = 100, nullable = false, updatable = false)
    private String documentType;

    /**
     * DBF-REG-028 — the owning version, {@code FK_REG_REQ_DOC_REG_SVC_PKG_VER} (REQ-REG-037).
     * An id, as the dbf-matrix names it — not an association.
     */
    @Column(name = "SERVICE_PACKAGE_VERSION_ID", nullable = false, updatable = false)
    private Long servicePackageVersionId;

    /** JPA only. */
    protected RequiredDocument() {
    }

    private RequiredDocument(Long servicePackageVersionId, String documentType) {
        this.servicePackageVersionId = servicePackageVersionId;
        this.documentType = documentType;
    }

    /**
     * A required document type as the load run stores it with its version, after every load
     * rule has accepted the package — this method stores, it does not decide.
     *
     * @param servicePackageVersionId the owning {@link ServicePackageVersion} id
     * @param documentType            the declared document type
     */
    public static RequiredDocument of(Long servicePackageVersionId, String documentType) {
        Objects.requireNonNull(servicePackageVersionId, "servicePackageVersionId");
        Objects.requireNonNull(documentType, "documentType");
        return new RequiredDocument(servicePackageVersionId, documentType);
    }

    public Long getRequiredDocumentId() {
        return requiredDocumentId;
    }

    public String getDocumentType() {
        return documentType;
    }

    public Long getServicePackageVersionId() {
        return servicePackageVersionId;
    }
}
