package io.agenticai.reg.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

import java.time.OffsetDateTime;
import java.util.Objects;

/**
 * ENT-REG-001 Service Package — one row of {@code REG_SVC_PKG} per service code (REQ-REG-001).
 * Kind {@code config}: no audit columns, no soft delete; a package is never deleted
 * (REQ-REG-026) — a service whose folder is gone is <em>withdrawn</em> (REQ-REG-010) and a
 * returning one is made available again (REQ-REG-011).
 *
 * <p>Persistence mapping plus the intention-revealing state methods of the {@code AVAILABLE}
 * flag. Every rule of this entity (RULE-REG-002, RULE-REG-016, RULE-REG-022) is owned by the
 * service layer (load run / registry service); the entity only executes the decided transition.
 * The load run is the only writer (ADR-REG-007); no request data is held (REQ-REG-059).
 */
@Entity
@Table(name = "REG_SVC_PKG",
        uniqueConstraints = {
                @UniqueConstraint(name = "UQ_REG_SVC_PKG_SERVICE_CODE", columnNames = {"SERVICE_CODE"})
        },
        indexes = {
                @Index(name = "IDX_REG_SVC_PKG_AVAILABLE", columnList = "AVAILABLE")
        })
public class ServicePackage {

    /** DBF-REG-001 — identity key, {@code NUMBER(19) GENERATED BY DEFAULT AS IDENTITY}. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "SERVICE_PACKAGE_ID", nullable = false, updatable = false)
    private Long servicePackageId;

    /**
     * DBF-REG-002 — the service code, unique and immutable, stored in canonical lower case
     * (REQ-REG-001, REQ-REG-006, REQ-REG-064, RULE-REG-022, ADR-REG-017). Canonicalisation
     * ({@code ServiceCodes.canonical}) happens in the load run before this entity is created.
     */
    @Column(name = "SERVICE_CODE", length = 100, nullable = false, updatable = false)
    private String serviceCode;

    /**
     * DBF-REG-003 — {@code 1} = available, {@code 0} = withdrawn (REQ-REG-010, REQ-REG-011,
     * REQ-REG-012, REQ-REG-014, REQ-REG-066); database default {@code 1},
     * {@code CHK_REG_SVC_PKG_AVAILABLE}. Changes only through {@link #withdraw(OffsetDateTime)}
     * and {@link #makeAvailable()}.
     */
    @Column(name = "AVAILABLE", nullable = false)
    private Boolean available;

    /** DBF-REG-004 — the first load of the service code (REQ-REG-006); never changes. */
    @Column(name = "REGISTERED_AT", nullable = false, updatable = false)
    private OffsetDateTime registeredAt;

    /**
     * DBF-REG-005 — set when withdrawn, cleared when available again (REQ-REG-010, REQ-REG-011);
     * {@code null} while available.
     */
    @Column(name = "WITHDRAWN_AT")
    private OffsetDateTime withdrawnAt;

    /** JPA only. */
    protected ServicePackage() {
    }

    private ServicePackage(String serviceCode, OffsetDateTime registeredAt) {
        this.serviceCode = serviceCode;
        this.available = Boolean.TRUE;
        this.registeredAt = registeredAt;
        this.withdrawnAt = null;
    }

    /**
     * A newly registered service package (REQ-REG-006): available, not withdrawn.
     *
     * @param serviceCode  the canonical service code (already trimmed and lower-cased, and already
     *                     accepted by RULE-REG-022 — the load run decides, this method stores)
     * @param registeredAt the time of the load run that first registered the code
     */
    public static ServicePackage register(String serviceCode, OffsetDateTime registeredAt) {
        Objects.requireNonNull(serviceCode, "serviceCode");
        Objects.requireNonNull(registeredAt, "registeredAt");
        return new ServicePackage(serviceCode, registeredAt);
    }

    /**
     * Marks the package withdrawn (REQ-REG-010, AC-REG-010): {@code available = false},
     * {@code withdrawnAt = at}. Stored versions stay untouched (ADR-REG-003).
     *
     * @param at the time of the load run that found the folder gone
     */
    public void withdraw(OffsetDateTime at) {
        Objects.requireNonNull(at, "at");
        this.available = Boolean.FALSE;
        this.withdrawnAt = at;
    }

    /**
     * Marks the package available again (REQ-REG-011, AC-REG-011): {@code available = true},
     * {@code withdrawnAt} cleared.
     */
    public void makeAvailable() {
        this.available = Boolean.TRUE;
        this.withdrawnAt = null;
    }

    public Long getServicePackageId() {
        return servicePackageId;
    }

    public String getServiceCode() {
        return serviceCode;
    }

    public boolean isAvailable() {
        return Boolean.TRUE.equals(available);
    }

    public OffsetDateTime getRegisteredAt() {
        return registeredAt;
    }

    /** {@code null} while the package is available. */
    public OffsetDateTime getWithdrawnAt() {
        return withdrawnAt;
    }
}
