package io.agenticai.reg.entity;

import io.agenticai.reg.domain.FetchMode;
import io.agenticai.reg.entity.converter.FetchModeConverter;
import jakarta.persistence.Column;
import jakarta.persistence.Convert;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Lob;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

import java.time.OffsetDateTime;
import java.util.Objects;

/**
 * ENT-REG-002 Service Package Version — one row of {@code REG_SVC_PKG_VER} per loaded version
 * of a service package (REQ-REG-019). Kind {@code config}: no audit columns.
 *
 * <p>Immutable once stored (ADR-REG-003, REQ-REG-026): a change to a package is a new version,
 * never an edit — so this class has no setter at all; the load run (ADR-REG-007), its only
 * writer, creates a row through {@link #loaded} and never changes it. The owning package is
 * referenced by its id ({@code SERVICE_PACKAGE_ID}, {@code FK_REG_SVC_PKG_VER_REG_SVC_PKG}), as
 * the dbf-matrix names it.
 *
 * <p>Every rule of this entity (RULE-REG-001, 003, 004, 008 … 012, 018, 020, 024, 026, 027) is
 * owned by the service layer (load run); the database backstops are
 * {@code UQ_REG_SVC_PKG_VER_PKG_VERSION} and the {@code CHK_REG_SVC_PKG_VER_*} constraints.
 * No request data is held (REQ-REG-059).
 */
@Entity
@Table(name = "REG_SVC_PKG_VER",
        uniqueConstraints = {
                @UniqueConstraint(name = "UQ_REG_SVC_PKG_VER_PKG_VERSION",
                        columnNames = {"SERVICE_PACKAGE_ID", "VERSION_NUMBER"})
        },
        indexes = {
                @Index(name = "IDX_REG_SVC_PKG_VER_SERVICE_PACKAGE_ID",
                        columnList = "SERVICE_PACKAGE_ID, LOADED_AT")
        })
public class ServicePackageVersion {

    /** DBF-REG-006 — identity key, {@code NUMBER(19) GENERATED BY DEFAULT AS IDENTITY}. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "SERVICE_PACKAGE_VERSION_ID", nullable = false, updatable = false)
    private Long servicePackageVersionId;

    /**
     * DBF-REG-007 — the declared version number, unique per service package (REQ-REG-019 …
     * REQ-REG-022, REQ-REG-070, RULE-REG-003, RULE-REG-004);
     * {@code CHK_REG_SVC_PKG_VER_VERSION_NUMBER} ≥ 1.
     */
    @Column(name = "VERSION_NUMBER", nullable = false, updatable = false)
    private Integer versionNumber;

    /**
     * DBF-REG-008 — the service knowledge file, whole and unaltered (REQ-REG-002, REQ-REG-018,
     * REQ-REG-027, REQ-REG-028, RULE-REG-018).
     */
    @Lob
    @Column(name = "SERVICE_KNOWLEDGE", nullable = false, updatable = false)
    private String serviceKnowledge;

    /**
     * DBF-REG-009 — the service definition file as loaded, kept for resolvability (REQ-REG-002,
     * REQ-REG-025, REQ-REG-034, REQ-REG-041, REQ-REG-071).
     */
    @Lob
    @Column(name = "SERVICE_DEFINITION", nullable = false, updatable = false)
    private String serviceDefinition;

    /** DBF-REG-010 — the name of the only bind parameter (REQ-REG-032, RULE-REG-006). */
    @Column(name = "INPUT_NAME", length = 100, nullable = false, updatable = false)
    private String inputName;

    /**
     * DBF-REG-011 — the fetch mode (REQ-REG-036, REQ-REG-038, RULE-REG-008), stored as
     * {@code path | blob | manual} through {@link FetchModeConverter}
     * ({@code CHK_REG_SVC_PKG_VER_FETCH_MODE}).
     */
    @Convert(converter = FetchModeConverter.class)
    @Column(name = "FETCH_MODE", length = 10, nullable = false, updatable = false)
    private FetchMode fetchMode;

    /**
     * DBF-REG-012 — the query that lists the documents; required for {@code path} / {@code blob}
     * (REQ-REG-039, REQ-REG-040, REQ-REG-070, REQ-REG-072, RULE-REG-009,
     * {@code CHK_REG_SVC_PKG_VER_DOC_SOURCE}). A query name, never a foreign key.
     */
    @Column(name = "DOCUMENT_SOURCE_QUERY_NAME", length = 100, updatable = false)
    private String documentSourceQueryName;

    /**
     * DBF-REG-013 — the column of the document source query holding the document type; required
     * for {@code path} / {@code blob} (REQ-REG-039, RULE-REG-009).
     */
    @Column(name = "DOCUMENT_TYPE_COLUMN", length = 128, updatable = false)
    private String documentTypeColumn;

    /**
     * DBF-REG-014 — the column holding the document location; required for {@code path}
     * (REQ-REG-039, REQ-REG-041, RULE-REG-009, {@code CHK_REG_SVC_PKG_VER_PATH_COLUMN}).
     */
    @Column(name = "DOCUMENT_PATH_COLUMN", length = 128, updatable = false)
    private String documentPathColumn;

    /**
     * DBF-REG-015 — the column holding the document content; required for {@code blob}
     * (REQ-REG-039, REQ-REG-040, RULE-REG-009, {@code CHK_REG_SVC_PKG_VER_CONTENT_COLUMN}).
     */
    @Column(name = "DOCUMENT_CONTENT_COLUMN", length = 128, updatable = false)
    private String documentContentColumn;

    /**
     * DBF-REG-016 — {@code 1} = the approval API is enabled (REQ-REG-042, REQ-REG-044,
     * REQ-REG-045); database default {@code 0}, {@code CHK_REG_SVC_PKG_VER_APPROVAL_ENABLED}.
     */
    @Column(name = "APPROVAL_ENABLED", nullable = false, updatable = false)
    private Boolean approvalEnabled;

    /**
     * DBF-REG-017 — the approval API definition (method + path pattern); required when enabled
     * (REQ-REG-042 … REQ-REG-044, RULE-REG-011, {@code CHK_REG_SVC_PKG_VER_APPROVAL_API}).
     */
    @Column(name = "APPROVAL_API", length = 500, updatable = false)
    private String approvalApi;

    /**
     * DBF-REG-018 — SHA-256 digest of both files, hex; detects in-place edits (REQ-REG-021,
     * REQ-REG-023, REQ-REG-069, RULE-REG-003).
     */
    @Column(name = "CONTENT_HASH", length = 64, nullable = false, updatable = false)
    private String contentHash;

    /** DBF-REG-019 — the load run that stored the version (REQ-REG-020). */
    @Column(name = "LOADED_AT", nullable = false, updatable = false)
    private OffsetDateTime loadedAt;

    /**
     * DBF-REG-020 — the owning service package, {@code FK_REG_SVC_PKG_VER_REG_SVC_PKG}
     * (REQ-REG-020, REQ-REG-024). An id, as the dbf-matrix names it — not an association.
     */
    @Column(name = "SERVICE_PACKAGE_ID", nullable = false, updatable = false)
    private Long servicePackageId;

    /** JPA only. */
    protected ServicePackageVersion() {
    }

    private ServicePackageVersion(Long servicePackageId,
                                  Integer versionNumber,
                                  String serviceKnowledge,
                                  String serviceDefinition,
                                  String inputName,
                                  FetchMode fetchMode,
                                  String documentSourceQueryName,
                                  String documentTypeColumn,
                                  String documentPathColumn,
                                  String documentContentColumn,
                                  Boolean approvalEnabled,
                                  String approvalApi,
                                  String contentHash,
                                  OffsetDateTime loadedAt) {
        this.servicePackageId = servicePackageId;
        this.versionNumber = versionNumber;
        this.serviceKnowledge = serviceKnowledge;
        this.serviceDefinition = serviceDefinition;
        this.inputName = inputName;
        this.fetchMode = fetchMode;
        this.documentSourceQueryName = documentSourceQueryName;
        this.documentTypeColumn = documentTypeColumn;
        this.documentPathColumn = documentPathColumn;
        this.documentContentColumn = documentContentColumn;
        this.approvalEnabled = approvalEnabled;
        this.approvalApi = approvalApi;
        this.contentHash = contentHash;
        this.loadedAt = loadedAt;
    }

    /**
     * A version as the load run stores it (REQ-REG-020), after every load rule has accepted the
     * package — this method stores, it does not decide. The required values are checked for
     * presence only; the optional document-source and approval values are stored as given
     * ({@code null} when the package does not declare them).
     *
     * @param servicePackageId        the owning {@link ServicePackage} id
     * @param versionNumber           the declared version number (≥ 1)
     * @param serviceKnowledge        the service knowledge file, whole
     * @param serviceDefinition       the service definition file, whole
     * @param inputName               the only bind parameter name
     * @param fetchMode               the fetch mode
     * @param documentSourceQueryName the document source query name, or {@code null} ({@code manual})
     * @param documentTypeColumn      the document type column, or {@code null} ({@code manual})
     * @param documentPathColumn      the document path column, or {@code null} (not {@code path})
     * @param documentContentColumn   the document content column, or {@code null} (not {@code blob})
     * @param approvalEnabled         whether the approval API is enabled
     * @param approvalApi             the approval API definition, or {@code null} when not enabled
     * @param contentHash             the SHA-256 digest of both files, hex
     * @param loadedAt                the time of the load run storing the version
     */
    public static ServicePackageVersion loaded(Long servicePackageId,
                                               int versionNumber,
                                               String serviceKnowledge,
                                               String serviceDefinition,
                                               String inputName,
                                               FetchMode fetchMode,
                                               String documentSourceQueryName,
                                               String documentTypeColumn,
                                               String documentPathColumn,
                                               String documentContentColumn,
                                               boolean approvalEnabled,
                                               String approvalApi,
                                               String contentHash,
                                               OffsetDateTime loadedAt) {
        Objects.requireNonNull(servicePackageId, "servicePackageId");
        Objects.requireNonNull(serviceKnowledge, "serviceKnowledge");
        Objects.requireNonNull(serviceDefinition, "serviceDefinition");
        Objects.requireNonNull(inputName, "inputName");
        Objects.requireNonNull(fetchMode, "fetchMode");
        Objects.requireNonNull(contentHash, "contentHash");
        Objects.requireNonNull(loadedAt, "loadedAt");
        return new ServicePackageVersion(servicePackageId, versionNumber, serviceKnowledge,
                serviceDefinition, inputName, fetchMode, documentSourceQueryName, documentTypeColumn,
                documentPathColumn, documentContentColumn, approvalEnabled, approvalApi, contentHash,
                loadedAt);
    }

    public Long getServicePackageVersionId() {
        return servicePackageVersionId;
    }

    public Integer getVersionNumber() {
        return versionNumber;
    }

    public String getServiceKnowledge() {
        return serviceKnowledge;
    }

    public String getServiceDefinition() {
        return serviceDefinition;
    }

    public String getInputName() {
        return inputName;
    }

    public FetchMode getFetchMode() {
        return fetchMode;
    }

    /** {@code null} for fetch mode {@code manual}. */
    public String getDocumentSourceQueryName() {
        return documentSourceQueryName;
    }

    /** {@code null} for fetch mode {@code manual}. */
    public String getDocumentTypeColumn() {
        return documentTypeColumn;
    }

    /** {@code null} unless the fetch mode is {@code path}. */
    public String getDocumentPathColumn() {
        return documentPathColumn;
    }

    /** {@code null} unless the fetch mode is {@code blob}. */
    public String getDocumentContentColumn() {
        return documentContentColumn;
    }

    public boolean isApprovalEnabled() {
        return Boolean.TRUE.equals(approvalEnabled);
    }

    /** {@code null} when the approval API is not enabled. */
    public String getApprovalApi() {
        return approvalApi;
    }

    public String getContentHash() {
        return contentHash;
    }

    public OffsetDateTime getLoadedAt() {
        return loadedAt;
    }

    public Long getServicePackageId() {
        return servicePackageId;
    }
}
