package io.agenticai.reg.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Lob;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

import java.util.Objects;

/**
 * ENT-REG-003 Service Query — one row of {@code REG_SVC_QUERY} per query of a stored version,
 * exactly as the service definition writes it (REQ-REG-029). Kind {@code config}: no audit
 * columns.
 *
 * <p>Created with its version and never changed (ADR-REG-003): no setters. The owning version is
 * referenced by its id ({@code SERVICE_PACKAGE_VERSION_ID}, {@code FK_REG_SVC_QUERY_REG_SVC_PKG_VER});
 * the connection is resolved by name (RULE-REG-005), never by a foreign key. Every rule of this
 * entity (RULE-REG-005, 006, 007, 017, 019) is owned by the service layer; the database backstop
 * is {@code UQ_REG_SVC_QUERY_VER_NAME}. The SQL text is configuration, not a query result
 * (REQ-REG-059).
 */
@Entity
@Table(name = "REG_SVC_QUERY",
        uniqueConstraints = {
                @UniqueConstraint(name = "UQ_REG_SVC_QUERY_VER_NAME",
                        columnNames = {"SERVICE_PACKAGE_VERSION_ID", "QUERY_NAME"})
        },
        indexes = {
                @Index(name = "IDX_REG_SVC_QUERY_SERVICE_PACKAGE_VERSION_ID",
                        columnList = "SERVICE_PACKAGE_VERSION_ID, CONNECTION_NAME"),
                @Index(name = "IDX_REG_SVC_QUERY_CONNECTION_NAME", columnList = "CONNECTION_NAME")
        })
public class ServiceQuery {

    /** DBF-REG-021 — identity key, {@code NUMBER(19) GENERATED BY DEFAULT AS IDENTITY}. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "SERVICE_QUERY_ID", nullable = false, updatable = false)
    private Long serviceQueryId;

    /** DBF-REG-022 — the declared query key, unique per version (REQ-REG-029, REQ-REG-035, RULE-REG-019). */
    @Column(name = "QUERY_NAME", length = 100, nullable = false, updatable = false)
    private String queryName;

    /**
     * DBF-REG-023 — the name of the connection the query runs on, resolved at supply time
     * (REQ-REG-029, REQ-REG-031, REQ-REG-053, RULE-REG-005, RULE-REG-017).
     */
    @Column(name = "CONNECTION_NAME", length = 100, nullable = false, updatable = false)
    private String connectionName;

    /**
     * DBF-REG-024 — the SQL text, one SELECT with the single named bind parameter, unaltered
     * (REQ-REG-029, REQ-REG-032, REQ-REG-033, RULE-REG-006, RULE-REG-007).
     */
    @Lob
    @Column(name = "SQL_TEXT", nullable = false, updatable = false)
    private String sqlText;

    /**
     * DBF-REG-025 — the owning version, {@code FK_REG_SVC_QUERY_REG_SVC_PKG_VER} (REQ-REG-025,
     * REQ-REG-029). An id, as the dbf-matrix names it — not an association.
     */
    @Column(name = "SERVICE_PACKAGE_VERSION_ID", nullable = false, updatable = false)
    private Long servicePackageVersionId;

    /** JPA only. */
    protected ServiceQuery() {
    }

    private ServiceQuery(Long servicePackageVersionId, String queryName, String connectionName, String sqlText) {
        this.servicePackageVersionId = servicePackageVersionId;
        this.queryName = queryName;
        this.connectionName = connectionName;
        this.sqlText = sqlText;
    }

    /**
     * A query as the load run stores it with its version, after every load rule has accepted
     * the package — this method stores, it does not decide.
     *
     * @param servicePackageVersionId the owning {@link ServicePackageVersion} id
     * @param queryName               the declared query key
     * @param connectionName          the declared connection name
     * @param sqlText                 the declared SQL text, unaltered
     */
    public static ServiceQuery of(Long servicePackageVersionId, String queryName, String connectionName, String sqlText) {
        Objects.requireNonNull(servicePackageVersionId, "servicePackageVersionId");
        Objects.requireNonNull(queryName, "queryName");
        Objects.requireNonNull(connectionName, "connectionName");
        Objects.requireNonNull(sqlText, "sqlText");
        return new ServiceQuery(servicePackageVersionId, queryName, connectionName, sqlText);
    }

    public Long getServiceQueryId() {
        return serviceQueryId;
    }

    public String getQueryName() {
        return queryName;
    }

    public String getConnectionName() {
        return connectionName;
    }

    public String getSqlText() {
        return sqlText;
    }

    public Long getServicePackageVersionId() {
        return servicePackageVersionId;
    }
}
