package io.agenticai.doc.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import org.hibernate.annotations.Immutable;

import java.time.OffsetDateTime;
import java.util.Objects;

/**
 * ENT-DOC-002 Ended Check — one row of {@code DOC_ENDED_CHECK} per Check whose end the Check
 * Engine has reported to DOC (REQ-DOC-060, ADR-DOC-015). Kind {@code transactional}: carries the
 * standard {@code createdAt} / {@code updatedAt} fields. PRIVATE to DOC and never exposed: the
 * marker that lets DOC refuse a late upload for that Check (RULE-DOC-009, REQ-DOC-061) and
 * drive the sweep of late uploads (REQ-DOC-062). DOC is tier 1 and cannot read the Check's
 * state, so it remembers which Checks it was told have ended.
 *
 * <p>Created once, never changed, not deleted in this version: this class has no setter at
 * all, every column is {@code updatable = false}, the class is {@link Immutable} and the only
 * way in is {@link #recorded}. One row per Check — {@code UQ_DOC_ENDED_CHECK_CHECK_ID}
 * (REQ-DOC-060: repeating the notice keeps one row; the INSERT-if-absent is the SVC-API
 * procedure's). The Check identifier is a VALUE handed in by the caller — no foreign key, no
 * read of RPT (ADR-DOC-003). No request data is held: one number per ended Check and the time.
 *
 * <p>No rule is owned by this entity's domain layer: RULE-DOC-009 reads it and is the
 * service's; nothing guards its own writes beyond the unique constraint.
 */
@Entity
@Immutable
@Table(name = "DOC_ENDED_CHECK",
        uniqueConstraints = {
                @UniqueConstraint(name = "UQ_DOC_ENDED_CHECK_CHECK_ID", columnNames = {"CHECK_ID"})
        })
public class EndedCheck {

    /** DBF-DOC-012 — identity key, {@code NUMBER(19) GENERATED BY DEFAULT AS IDENTITY}. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ENDED_CHECK_ID", nullable = false, updatable = false)
    private Long endedCheckId;

    /**
     * DBF-DOC-013 — the identifier of the ended Check (REQ-DOC-060, REQ-DOC-061, REQ-DOC-062),
     * as a value handed in with the end-of-Check notice; unique
     * ({@code UQ_DOC_ENDED_CHECK_CHECK_ID}), which also serves the RULE-DOC-009 lookup and the
     * sweep semi-join. Never a foreign key (ADR-DOC-003).
     */
    @Column(name = "CHECK_ID", nullable = false, updatable = false)
    private Long checkId;

    /**
     * DBF-DOC-014 — standard field ({@code entity_defaults.transactional}, REQ-DOC-060): the
     * time the end of the Check was reported, filled by the database
     * ({@code DEFAULT SYSTIMESTAMP}, no trigger) — mapped read-only, never set from code or
     * request data.
     */
    @Column(name = "CREATED_AT", nullable = false, insertable = false, updatable = false)
    private OffsetDateTime createdAt;

    /**
     * DBF-DOC-015 — standard field ({@code entity_defaults.transactional}, REQ-DOC-060), filled
     * by the database ({@code DEFAULT SYSTIMESTAMP}, no trigger) — mapped read-only. An Ended
     * Check is never updated, so the insert-time default is its final value and equals
     * {@link #createdAt}.
     */
    @Column(name = "UPDATED_AT", nullable = false, insertable = false, updatable = false)
    private OffsetDateTime updatedAt;

    /** JPA only. */
    protected EndedCheck() {
    }

    private EndedCheck(Long checkId) {
        this.checkId = checkId;
    }

    /**
     * An Ended Check as the end-of-Check procedure records it (REQ-DOC-060, ADR-DOC-015) — this
     * method stores, it does not decide. Whether the Check is already recorded (one row per
     * Check) is the procedure's INSERT-if-absent, backstopped by
     * {@code UQ_DOC_ENDED_CHECK_CHECK_ID}.
     *
     * @param checkId the identifier of the Check whose end was reported (a value, never a key)
     */
    public static EndedCheck recorded(Long checkId) {
        Objects.requireNonNull(checkId, "checkId");
        return new EndedCheck(checkId);
    }

    public Long getEndedCheckId() {
        return endedCheckId;
    }

    public Long getCheckId() {
        return checkId;
    }

    /** Database-filled; {@code null} on an instance not yet reloaded after its insert. */
    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    /** Database-filled; {@code null} on an instance not yet reloaded after its insert. */
    public OffsetDateTime getUpdatedAt() {
        return updatedAt;
    }
}
