package io.agenticai.doc.entity;

import jakarta.persistence.Basic;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Lob;
import jakarta.persistence.Table;
import org.hibernate.annotations.Immutable;

import java.time.OffsetDateTime;
import java.util.Objects;

/**
 * ENT-DOC-001 Uploaded Document — one row of {@code DOC_UPLOADED_DOC} per file handed over for
 * one Check in {@code manual} fetch mode (REQ-DOC-017, REQ-DOC-018). Kind {@code transactional}:
 * carries the standard {@code createdAt} / {@code updatedAt} fields. PRIVATE to DOC — held only
 * until its Check ends, then hard-deleted (REQ-DOC-054, REQ-DOC-062, ADR-DOC-008, ADR-DOC-015).
 *
 * <p>Never changed after it is created (RULE-DOC-004, REQ-DOC-023, ADR-DOC-006): a corrected
 * file is a new upload. This class therefore has no setter at all, every column is
 * {@code updatable = false}, the class is {@link Immutable} (Hibernate skips dirty checking and
 * refuses an update), and the only way in is {@link #handedOver}. The rule has nothing to
 * decide at runtime — it is enforced structurally here and by the absence of any update
 * operation in the SVC-API procedures — so no domain class exists for it.
 *
 * <p>The Check identifier, the service code and the version number are VALUES handed in by the
 * caller — no foreign key, no association, no read of RPT or REG from this mapping
 * (ADR-DOC-003, ADR-DOC-006, ADR-DOC-010). The table carries no unique constraint: several
 * uploads of one document type per Check are allowed (ADR-DOC-006).
 *
 * <p>Every other rule of this entity is owned by the service or the repository layer:
 * RULE-DOC-001 / RULE-DOC-002 (fetch mode and document type of the version), RULE-DOC-003
 * (complete upload — {@code CHK_DOC_UPLOADED_DOC_FILE_SIZE} backstops {@code fileSize > 0}),
 * RULE-DOC-005 (oversized upload kept without content — {@code CHK_DOC_UPLOADED_DOC_CONTENT}
 * ties {@code CONTENT IS NULL} to {@code OVERSIZED = 1}), RULE-DOC-008 (every read filters by
 * {@code CHECK_ID}), RULE-DOC-009 (no upload for an Ended Check) and RULE-DOC-010 (maximum
 * uploads per Check, {@code aias.check.max-uploads}). The remaining database backstops are
 * {@code CHK_DOC_UPLOADED_DOC_OVERSIZED} and {@code CHK_DOC_UPLOADED_DOC_VERSION_NUMBER}.
 */
@Entity
@Immutable
@Table(name = "DOC_UPLOADED_DOC",
        indexes = {
                @Index(name = "IDX_DOC_UPLOADED_DOC_CHECK_ID", columnList = "CHECK_ID")
        })
public class UploadedDocument {

    /** DBF-DOC-001 — identity key, {@code NUMBER(19) GENERATED BY DEFAULT AS IDENTITY}. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "UPLOADED_DOCUMENT_ID", nullable = false, updatable = false)
    private Long uploadedDocumentId;

    /**
     * DBF-DOC-002 — the Check this upload belongs to (REQ-DOC-017, REQ-DOC-018, REQ-DOC-054),
     * as a value handed over by the caller; indexed by {@code IDX_DOC_UPLOADED_DOC_CHECK_ID}
     * for the per-Check listing, count, fetch and delete. Never a foreign key: DOC does not read
     * RPT (ADR-DOC-003).
     */
    @Column(name = "CHECK_ID", nullable = false, updatable = false)
    private Long checkId;

    /**
     * DBF-DOC-003 — the service code of the Check (REQ-DOC-017, REQ-DOC-020), stored as the
     * caller handed it over. Open data from the registry — a {@code String}, never an enum,
     * never a foreign key (ADR-DOC-006).
     */
    @Column(name = "SERVICE_CODE", length = 100, nullable = false, updatable = false)
    private String serviceCode;

    /**
     * DBF-DOC-004 — the service package version of the Check (REQ-DOC-017, REQ-DOC-020,
     * REQ-DOC-021), stored as a value; {@code CHK_DOC_UPLOADED_DOC_VERSION_NUMBER} ≥ 1.
     */
    @Column(name = "VERSION_NUMBER", nullable = false, updatable = false)
    private Integer versionNumber;

    /**
     * DBF-DOC-005 — the document type the employee gave (REQ-DOC-017, REQ-DOC-021,
     * REQ-DOC-022, REQ-DOC-035); one of the version's required types, decided by the service
     * (RULE-DOC-002). Open data from the registry — a {@code String}, never an enum.
     */
    @Column(name = "DOCUMENT_TYPE", length = 100, nullable = false, updatable = false)
    private String documentType;

    /** DBF-DOC-006 — the file name as uploaded (REQ-DOC-017); shown back in the outcome detail. */
    @Column(name = "FILE_NAME", length = 255, nullable = false, updatable = false)
    private String fileName;

    /**
     * DBF-DOC-007 — the size of the uploaded file in bytes (REQ-DOC-017, REQ-DOC-022,
     * REQ-DOC-043), computed by the handover; greater than 0
     * ({@code CHK_DOC_UPLOADED_DOC_FILE_SIZE}, RULE-DOC-003). Kept even when the content is not.
     */
    @Column(name = "FILE_SIZE", nullable = false, updatable = false)
    private Long fileSize;

    /**
     * DBF-DOC-008 — the uploaded file itself, {@code BLOB} (REQ-DOC-017, REQ-DOC-018,
     * REQ-DOC-023, REQ-DOC-043); {@code NULL} exactly when {@link #oversized}
     * ({@code CHK_DOC_UPLOADED_DOC_CONTENT}, RULE-DOC-005). Mapped as a lazily fetched
     * {@code @Lob byte[]} (CORE R1): the per-Check listing (QR-DOC-001) is a projection that
     * never selects this column, and the lazy hint keeps the column out of any entity load that
     * does not need it. Document content is data, never instructions (guardrail G7); it leaves
     * DOC only inside a Document Outcome for the fetching call (ADR-DOC-008).
     */
    @Lob
    @Basic(fetch = FetchType.LAZY)
    @Column(name = "CONTENT", updatable = false)
    private byte[] content;

    /**
     * DBF-DOC-009 — {@code 1} = the file was larger than the maximum file size
     * ({@code aias.check.max-file-size}) and its content was not kept (REQ-DOC-043,
     * REQ-DOC-044, RULE-DOC-005); set once by the handover. Database default {@code 0},
     * {@code CHK_DOC_UPLOADED_DOC_OVERSIZED} — the factory always sets it explicitly.
     */
    @Column(name = "OVERSIZED", nullable = false, updatable = false)
    private Boolean oversized;

    /**
     * DBF-DOC-010 — standard field ({@code entity_defaults.transactional}, REQ-DOC-017): the
     * upload time, filled by the database ({@code DEFAULT SYSTIMESTAMP}, no trigger) — mapped
     * read-only, never set from code or request data.
     */
    @Column(name = "CREATED_AT", nullable = false, insertable = false, updatable = false)
    private OffsetDateTime createdAt;

    /**
     * DBF-DOC-011 — standard field ({@code entity_defaults.transactional}, REQ-DOC-017), filled
     * by the database ({@code DEFAULT SYSTIMESTAMP}, no trigger) — mapped read-only. An Uploaded
     * Document is never updated (RULE-DOC-004), so the insert-time default is its final value and
     * equals {@link #createdAt}.
     */
    @Column(name = "UPDATED_AT", nullable = false, insertable = false, updatable = false)
    private OffsetDateTime updatedAt;

    /** JPA only. */
    protected UploadedDocument() {
    }

    private UploadedDocument(Long checkId,
                             String serviceCode,
                             Integer versionNumber,
                             String documentType,
                             String fileName,
                             Long fileSize,
                             byte[] content,
                             Boolean oversized) {
        this.checkId = checkId;
        this.serviceCode = serviceCode;
        this.versionNumber = versionNumber;
        this.documentType = documentType;
        this.fileName = fileName;
        this.fileSize = fileSize;
        this.content = content;
        this.oversized = oversized;
    }

    /**
     * An Uploaded Document as the handover stores it (REQ-DOC-017, REQ-DOC-043, ADR-DOC-006),
     * after every handover rule has accepted the upload — this method stores, it does not
     * decide. Whether the version is {@code manual} (RULE-DOC-001), the document type is one of
     * its required types (RULE-DOC-002), the upload is complete (RULE-DOC-003), the file
     * exceeds the maximum file size (RULE-DOC-005), the Check has ended (RULE-DOC-009) and the
     * Check is below its upload limit (RULE-DOC-010) are the service's rules, applied before
     * this call; the CHECK constraints backstop them. The required values are checked for
     * presence only, plus the one representation invariant of the row —
     * {@code content == null} exactly when {@code oversized} ({@code CHK_DOC_UPLOADED_DOC_CONTENT})
     * — which a caller can only break by programming error.
     *
     * @param checkId       the Check's identifier, as handed over (a value, never a key)
     * @param serviceCode   the service code of the Check, as handed over
     * @param versionNumber the service package version of the Check, as handed over (≥ 1)
     * @param documentType  the document type the employee gave
     * @param fileName      the file name as uploaded
     * @param fileSize      the size of the uploaded file in bytes (&gt; 0)
     * @param content       the file content, or {@code null} when {@code oversized}
     * @param oversized     whether the file exceeded the maximum file size and its content was
     *                      not kept
     * @throws IllegalArgumentException when {@code content} and {@code oversized} disagree
     */
    public static UploadedDocument handedOver(Long checkId,
                                              String serviceCode,
                                              Integer versionNumber,
                                              String documentType,
                                              String fileName,
                                              Long fileSize,
                                              byte[] content,
                                              boolean oversized) {
        Objects.requireNonNull(checkId, "checkId");
        Objects.requireNonNull(serviceCode, "serviceCode");
        Objects.requireNonNull(versionNumber, "versionNumber");
        Objects.requireNonNull(documentType, "documentType");
        Objects.requireNonNull(fileName, "fileName");
        Objects.requireNonNull(fileSize, "fileSize");
        if ((content == null) != oversized) {
            throw new IllegalArgumentException(
                    "content must be null exactly when oversized (CHK_DOC_UPLOADED_DOC_CONTENT)");
        }
        return new UploadedDocument(checkId, serviceCode, versionNumber, documentType, fileName,
                fileSize, content, oversized);
    }

    public Long getUploadedDocumentId() {
        return uploadedDocumentId;
    }

    public Long getCheckId() {
        return checkId;
    }

    public String getServiceCode() {
        return serviceCode;
    }

    public Integer getVersionNumber() {
        return versionNumber;
    }

    public String getDocumentType() {
        return documentType;
    }

    public String getFileName() {
        return fileName;
    }

    public Long getFileSize() {
        return fileSize;
    }

    /**
     * The stored file, or {@code null} when {@link #isOversized() oversized}. The array is the
     * stored content itself — read it, never write into it (RULE-DOC-004); a defensive copy of a
     * file up to the maximum file size is deliberately not made.
     */
    public byte[] getContent() {
        return content;
    }

    public boolean isOversized() {
        return Boolean.TRUE.equals(oversized);
    }

    /** Database-filled; {@code null} on an instance not yet reloaded after its insert. */
    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    /** Database-filled; {@code null} on an instance not yet reloaded after its insert. */
    public OffsetDateTime getUpdatedAt() {
        return updatedAt;
    }
}
