package io.agenticai.rpt.entity;

import io.agenticai.rpt.domain.DocumentReadStatus;
import io.agenticai.rpt.domain.FetchMode;
import io.agenticai.rpt.domain.UnreadableReason;
import io.agenticai.rpt.entity.converter.DocumentReadStatusConverter;
import io.agenticai.rpt.entity.converter.FetchModeConverter;
import io.agenticai.rpt.entity.converter.UnreadableReasonConverter;
import jakarta.persistence.Column;
import jakarta.persistence.Convert;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Lob;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import org.hibernate.annotations.Immutable;

import java.time.OffsetDateTime;
import java.util.Objects;

/**
 * ENT-RPT-003 Check Document — one row of {@code RPT_CHECK_DOCUMENT} per document outcome of a
 * completed report (ADR-RPT-001, REQ-RPT-011). Kind {@code transactional}: carries the standard
 * {@code createdAt} / {@code updatedAt} fields. No document content exists in any column
 * (REQ-RPT-019): the outcome only.
 *
 * <p>Inserted once by {@code completeCheck} and never updated (REQ-RPT-020): no setter, every
 * column {@code updatable = false}, the class is {@link Immutable} and the only way in is
 * {@link #recorded}. Leaves only with its Check Run ({@code FK_RPT_CHECK_DOCUMENT_RPT_CHECK_RUN}
 * {@code ON DELETE CASCADE}, the database's). The owning Check Run is referenced by its id, as the
 * dbf-matrix names it — not an association. One position per report:
 * {@code UQ_RPT_CHECK_DOCUMENT_RUN_POS} (REQ-RPT-010).
 *
 * <p>RULE-RPT-008 (reason exactly on UNREADABLE; type and source mode required, owner layer
 * domain) is decided by {@code SubmittedReport} before this factory is called;
 * {@code CHK_RPT_CHECK_DOCUMENT_REASON} backstops it. {@code documentType} is open data of the
 * service registry — a {@code String}, never an enum.
 */
@Entity
@Immutable
@Table(name = "RPT_CHECK_DOCUMENT",
        uniqueConstraints = {
                @UniqueConstraint(name = "UQ_RPT_CHECK_DOCUMENT_RUN_POS",
                        columnNames = {"CHECK_RUN_ID", "POSITION"})
        })
public class CheckDocument {

    /** DBF-RPT-030 — identity key, {@code NUMBER(19) GENERATED BY DEFAULT AS IDENTITY}. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "CHECK_DOCUMENT_ID", nullable = false, updatable = false)
    private Long checkDocumentId;

    /** DBF-RPT-031 — order of the outcome in the report, from 1 ({@code CHK_RPT_CHECK_DOCUMENT_POSITION}). */
    @Column(name = "POSITION", nullable = false, updatable = false)
    private Integer position;

    /** DBF-RPT-032 — the document type as carried by CHK; a value only. */
    @Column(name = "DOCUMENT_TYPE", length = 100, nullable = false, updatable = false)
    private String documentType;

    /** DBF-RPT-033 — {@code path | blob | manual} through {@link FetchModeConverter}. */
    @Convert(converter = FetchModeConverter.class)
    @Column(name = "SOURCE_MODE", length = 10, nullable = false, updatable = false)
    private FetchMode sourceMode;

    /** DBF-RPT-034 — the read status through {@link DocumentReadStatusConverter}. */
    @Convert(converter = DocumentReadStatusConverter.class)
    @Column(name = "READ_STATUS", length = 30, nullable = false, updatable = false)
    private DocumentReadStatus readStatus;

    /** DBF-RPT-035 — present exactly when UNREADABLE, through {@link UnreadableReasonConverter}. */
    @Convert(converter = UnreadableReasonConverter.class)
    @Column(name = "UNREADABLE_REASON", length = 30, updatable = false)
    private UnreadableReason unreadableReason;

    /** DBF-RPT-036 — detail text; never document content (REQ-RPT-019). */
    @Lob
    @Column(name = "DETAIL", updatable = false)
    private String detail;

    /** DBF-RPT-037 — the owning Check Run, {@code FK_RPT_CHECK_DOCUMENT_RPT_CHECK_RUN} (ON DELETE CASCADE). */
    @Column(name = "CHECK_RUN_ID", nullable = false, updatable = false)
    private Long checkRunId;

    /** DBF-RPT-038 — standard field, database-filled ({@code DEFAULT SYSTIMESTAMP}); mapped read-only. */
    @Column(name = "CREATED_AT", nullable = false, insertable = false, updatable = false)
    private OffsetDateTime createdAt;

    /** DBF-RPT-039 — standard field, database-filled; never changed after insert (REQ-RPT-020). */
    @Column(name = "UPDATED_AT", nullable = false, insertable = false, updatable = false)
    private OffsetDateTime updatedAt;

    /** JPA only. */
    protected CheckDocument() {
    }

    private CheckDocument(Long checkRunId, Integer position, String documentType,
                          FetchMode sourceMode, DocumentReadStatus readStatus,
                          UnreadableReason unreadableReason, String detail) {
        this.checkRunId = checkRunId;
        this.position = position;
        this.documentType = documentType;
        this.sourceMode = sourceMode;
        this.readStatus = readStatus;
        this.unreadableReason = unreadableReason;
        this.detail = detail;
    }

    /**
     * A document outcome as {@code completeCheck} stores it — this method stores, it does not
     * decide (RULE-RPT-008 is decided before). Required values are checked for presence only; the
     * optional ones are stored as given.
     *
     * @param checkRunId       the owning Check Run id
     * @param position         the order in the report, from 1 (index as received)
     * @param documentType     the document type
     * @param sourceMode       the source mode
     * @param readStatus       the read status
     * @param unreadableReason the reason, or {@code null} unless UNREADABLE
     * @param detail           the detail text, or {@code null}
     * @throws IllegalArgumentException when {@code position} is below 1 (API misuse)
     */
    public static CheckDocument recorded(Long checkRunId, int position, String documentType,
                                         FetchMode sourceMode, DocumentReadStatus readStatus,
                                         UnreadableReason unreadableReason, String detail) {
        Objects.requireNonNull(checkRunId, "checkRunId");
        Objects.requireNonNull(documentType, "documentType");
        Objects.requireNonNull(sourceMode, "sourceMode");
        Objects.requireNonNull(readStatus, "readStatus");
        if (position < 1) {
            throw new IllegalArgumentException("position must be 1 or more: " + position);
        }
        return new CheckDocument(checkRunId, position, documentType, sourceMode, readStatus,
                unreadableReason, detail);
    }

    public Long getCheckDocumentId() {
        return checkDocumentId;
    }

    public Integer getPosition() {
        return position;
    }

    public String getDocumentType() {
        return documentType;
    }

    public FetchMode getSourceMode() {
        return sourceMode;
    }

    public DocumentReadStatus getReadStatus() {
        return readStatus;
    }

    /** {@code null} unless the read status is UNREADABLE. */
    public UnreadableReason getUnreadableReason() {
        return unreadableReason;
    }

    /** {@code null} when no detail was given. */
    public String getDetail() {
        return detail;
    }

    public Long getCheckRunId() {
        return checkRunId;
    }

    /** Database-filled; {@code null} on an instance not yet reloaded after its insert. */
    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    /** Database-filled; {@code null} on an instance not yet reloaded after its insert. */
    public OffsetDateTime getUpdatedAt() {
        return updatedAt;
    }
}
