package io.agenticai.rpt.entity;

import io.agenticai.rpt.domain.CheckFailureReason;
import io.agenticai.rpt.domain.CheckStatus;
import io.agenticai.rpt.domain.EmployeeDecision;
import io.agenticai.rpt.domain.FetchMode;
import io.agenticai.rpt.domain.OverallStatus;
import io.agenticai.rpt.entity.converter.CheckFailureReasonConverter;
import io.agenticai.rpt.entity.converter.CheckStatusConverter;
import io.agenticai.rpt.entity.converter.EmployeeDecisionConverter;
import io.agenticai.rpt.entity.converter.FetchModeConverter;
import io.agenticai.rpt.entity.converter.OverallStatusConverter;
import jakarta.persistence.Column;
import jakarta.persistence.Convert;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Lob;
import jakarta.persistence.Table;

import java.time.OffsetDateTime;
import java.util.Objects;

/**
 * ENT-RPT-001 Check Run — one row of {@code RPT_CHECK_RUN} per Check: what it verified, its
 * status, its result or failure, and the Employee Decision beside the result (ADR-RPT-001,
 * ADR-RPT-003). Kind {@code transactional}: carries the standard {@code createdAt} /
 * {@code updatedAt} fields. Its {@code checkRunId} is the Check identifier ({@code checkId})
 * that CHK, DOC and INT hold by value (CON-RPT-001).
 *
 * <p>Life cycle (STATE MACHINE of DATA-DOM, {@code CHECK_STATUS}): created by {@link #created}
 * as {@code AWAITING_DOCUMENTS} ({@code manual}) or {@code RUNNING} ({@code path} / {@code blob});
 * {@code AWAITING_DOCUMENTS → RUNNING} and {@code RUNNING → RUNNING} through {@link #markRunning}
 * (keeps the first {@code runningSince}); {@code RUNNING → COMPLETED} through {@link #complete};
 * {@code AWAITING_DOCUMENTS | RUNNING → FAILED} through {@link #fail}; COMPLETED and FAILED are
 * terminal. The Employee Decision is not a status: {@link #recordDecision} writes it beside a
 * COMPLETED result. No setter exists.
 *
 * <p>The entity EXECUTES; it does not decide. Every rule of this entity is owned by the domain
 * layer and decided before a state method is called: RULE-RPT-001 / 002 / 006 at creation by
 * {@code CheckRunOpening}, RULE-RPT-003 by {@code CheckStatusTransition}, RULE-RPT-004 / 005 by
 * {@code SubmittedReport}, RULE-RPT-010 by {@code CheckFailure}, RULE-RPT-011 … 014 by
 * {@code DecisionRecording} (all in {@code io.agenticai.rpt.domain}). The repository guards of
 * RULE-RPT-003 / 011 / 012 (the conditional UPDATEs of SVC-API) and the CHECK constraints
 * ({@code CHK_RPT_CHECK_RUN_RESULT}, {@code _AWAITING}, {@code _DECISION}, {@code _ENDED_AT},
 * the closed lists) backstop them in the database.
 *
 * <p>The host identifiers {@code requestNumber}, {@code employeeId} and {@code decidedBy} are
 * plain strings exactly as received (REQ-RPT-002) — never keys; {@code serviceCode} is open data
 * of the service registry, a value, never an enum or a foreign key.
 */
@Entity
@Table(name = "RPT_CHECK_RUN",
        indexes = {
                @Index(name = "IDX_RPT_CHECK_RUN_SVC_REQ",
                        columnList = "SERVICE_CODE, REQUEST_NUMBER, STARTED_AT"),
                @Index(name = "IDX_RPT_CHECK_RUN_CHECK_STATUS", columnList = "CHECK_STATUS"),
                @Index(name = "IDX_RPT_CHECK_RUN_ENDED_AT", columnList = "ENDED_AT")
        })
public class CheckRun {

    /** DBF-RPT-001 — identity key, {@code NUMBER(19) GENERATED BY DEFAULT AS IDENTITY}; exposed as {@code checkId}. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "CHECK_RUN_ID", nullable = false, updatable = false)
    private Long checkRunId;

    /** DBF-RPT-002 — the service code as carried by CHK; a value, never a foreign key. */
    @Column(name = "SERVICE_CODE", length = 100, nullable = false, updatable = false)
    private String serviceCode;

    /** DBF-RPT-003 — the service package version number ({@code CHK_RPT_CHECK_RUN_VERSION_NUMBER} ≥ 1). */
    @Column(name = "VERSION_NUMBER", nullable = false, updatable = false)
    private Integer versionNumber;

    /** DBF-RPT-004 — {@code path | blob | manual} through {@link FetchModeConverter}. */
    @Convert(converter = FetchModeConverter.class)
    @Column(name = "FETCH_MODE", length = 10, nullable = false, updatable = false)
    private FetchMode fetchMode;

    /** DBF-RPT-005 — the host request number exactly as sent (REQ-RPT-002); never a foreign key. */
    @Column(name = "REQUEST_NUMBER", length = 100, nullable = false, updatable = false)
    private String requestNumber;

    /** DBF-RPT-006 — the employee who started the Check, exactly as sent (REQ-RPT-002); never a foreign key. */
    @Column(name = "EMPLOYEE_ID", length = 100, nullable = false, updatable = false)
    private String employeeId;

    /** DBF-RPT-007 — the Check status through {@link CheckStatusConverter}; forward only (RULE-RPT-003). */
    @Convert(converter = CheckStatusConverter.class)
    @Column(name = "CHECK_STATUS", length = 30, nullable = false)
    private CheckStatus checkStatus;

    /** DBF-RPT-008 — the start time handed over by CHK. */
    @Column(name = "STARTED_AT", nullable = false, updatable = false)
    private OffsetDateTime startedAt;

    /** DBF-RPT-009 — set by the first mark RUNNING, kept by every later one. */
    @Column(name = "RUNNING_SINCE")
    private OffsetDateTime runningSince;

    /** DBF-RPT-010 — set exactly when COMPLETED or FAILED; the purge measures age from it. */
    @Column(name = "ENDED_AT")
    private OffsetDateTime endedAt;

    /** DBF-RPT-011 — present exactly when COMPLETED, through {@link OverallStatusConverter}. */
    @Convert(converter = OverallStatusConverter.class)
    @Column(name = "OVERALL_STATUS", length = 30)
    private OverallStatus overallStatus;

    /** DBF-RPT-012 — the comparison model identifier of the report metadata; present exactly when COMPLETED. */
    @Column(name = "COMPARISON_MODEL", length = 200)
    private String comparisonModel;

    /** DBF-RPT-013 — present exactly when FAILED, through {@link CheckFailureReasonConverter}. */
    @Convert(converter = CheckFailureReasonConverter.class)
    @Column(name = "FAILURE_REASON", length = 30)
    private CheckFailureReason failureReason;

    /** DBF-RPT-014 — the failure detail text; present when FAILED (not blank — RULE-RPT-010). */
    @Lob
    @Column(name = "FAILURE_DETAIL")
    private String failureDetail;

    /** DBF-RPT-015 — the Employee Decision through {@link EmployeeDecisionConverter}; at most once, COMPLETED only. */
    @Convert(converter = EmployeeDecisionConverter.class)
    @Column(name = "EMPLOYEE_DECISION", length = 30)
    private EmployeeDecision employeeDecision;

    /** DBF-RPT-016 — the deciding employee exactly as sent (REQ-RPT-002); present exactly with the decision. */
    @Column(name = "DECIDED_BY", length = 100)
    private String decidedBy;

    /** DBF-RPT-017 — the recording time of the decision (ADR-RPT-009). */
    @Column(name = "DECIDED_AT")
    private OffsetDateTime decidedAt;

    /** DBF-RPT-018 — {@code NUMBER(1)}: 1 when executed through the Approval API, 0 otherwise (REQ-RPT-036); present exactly with the decision. */
    @Column(name = "APPROVAL_API_EXECUTED")
    private Boolean approvalApiExecuted;

    /**
     * DBF-RPT-019 — standard field ({@code entity_defaults.transactional}), filled by the database
     * ({@code DEFAULT SYSTIMESTAMP}, no trigger) — mapped read-only, never set from code or
     * request data; never exposed.
     */
    @Column(name = "CREATED_AT", nullable = false, insertable = false, updatable = false)
    private OffsetDateTime createdAt;

    /**
     * DBF-RPT-020 — standard field, filled by the database ({@code DEFAULT SYSTIMESTAMP}) — mapped
     * read-only. Every SVC-API UPDATE of this row sets {@code UPDATED_AT = SYSTIMESTAMP} in its own
     * statement; this mapping never writes it. Never exposed.
     */
    @Column(name = "UPDATED_AT", nullable = false, insertable = false, updatable = false)
    private OffsetDateTime updatedAt;

    /** JPA only. */
    protected CheckRun() {
    }

    private CheckRun(String serviceCode,
                     Integer versionNumber,
                     FetchMode fetchMode,
                     String requestNumber,
                     String employeeId,
                     CheckStatus checkStatus,
                     OffsetDateTime startedAt) {
        this.serviceCode = serviceCode;
        this.versionNumber = versionNumber;
        this.fetchMode = fetchMode;
        this.requestNumber = requestNumber;
        this.employeeId = employeeId;
        this.checkStatus = checkStatus;
        this.startedAt = startedAt;
    }

    /**
     * A Check Run as {@code createCheckRun} stores it (REQ-RPT-001) — this method stores, it does
     * not decide: RULE-RPT-001 (complete, not blank), RULE-RPT-006 (initial status a creation
     * code) and RULE-RPT-002 (status agrees with the fetch mode) are decided by
     * {@code CheckRunOpening} before this call. Every result and decision column stays
     * {@code null}; the identifiers are stored exactly as received.
     */
    public static CheckRun created(String serviceCode,
                                   Integer versionNumber,
                                   FetchMode fetchMode,
                                   String requestNumber,
                                   String employeeId,
                                   CheckStatus initialStatus,
                                   OffsetDateTime startedAt) {
        Objects.requireNonNull(serviceCode, "serviceCode");
        Objects.requireNonNull(versionNumber, "versionNumber");
        Objects.requireNonNull(fetchMode, "fetchMode");
        Objects.requireNonNull(requestNumber, "requestNumber");
        Objects.requireNonNull(employeeId, "employeeId");
        Objects.requireNonNull(initialStatus, "initialStatus");
        Objects.requireNonNull(startedAt, "startedAt");
        return new CheckRun(serviceCode, versionNumber, fetchMode, requestNumber, employeeId,
                initialStatus, startedAt);
    }

    /**
     * Executes {@code AWAITING_DOCUMENTS → RUNNING} or {@code RUNNING → RUNNING} (REQ-RPT-005):
     * the first {@code runningSince} is kept. Allowed only after
     * {@code CheckStatusTransition#refusalToMarkRunning()} found nothing to refuse.
     *
     * @param runningSince the time the Check Engine marks the Check running
     */
    public void markRunning(OffsetDateTime runningSince) {
        Objects.requireNonNull(runningSince, "runningSince");
        this.checkStatus = CheckStatus.RUNNING;
        if (this.runningSince == null) {
            this.runningSince = runningSince;
        }
    }

    /**
     * Executes {@code RUNNING → COMPLETED} (REQ-RPT-008), after {@code CheckStatusTransition} and
     * {@code SubmittedReport} found nothing to refuse (RULE-RPT-003, 004 … 008).
     *
     * @param overallStatus   the Overall Status of the report
     * @param comparisonModel the comparison model identifier of the report metadata
     * @param endedAt         the end time of the report metadata
     */
    public void complete(OverallStatus overallStatus, String comparisonModel, OffsetDateTime endedAt) {
        Objects.requireNonNull(overallStatus, "overallStatus");
        Objects.requireNonNull(comparisonModel, "comparisonModel");
        Objects.requireNonNull(endedAt, "endedAt");
        this.checkStatus = CheckStatus.COMPLETED;
        this.overallStatus = overallStatus;
        this.comparisonModel = comparisonModel;
        this.endedAt = endedAt;
    }

    /**
     * Executes {@code AWAITING_DOCUMENTS | RUNNING → FAILED} (REQ-RPT-018), after
     * {@code CheckStatusTransition} and {@code CheckFailure} found nothing to refuse
     * (RULE-RPT-003, RULE-RPT-010). Overall Status and comparison model stay {@code null}.
     *
     * @param failureReason the failure reason
     * @param failureDetail the failure detail text
     * @param endedAt       the end time
     */
    public void fail(CheckFailureReason failureReason, String failureDetail, OffsetDateTime endedAt) {
        Objects.requireNonNull(failureReason, "failureReason");
        Objects.requireNonNull(failureDetail, "failureDetail");
        Objects.requireNonNull(endedAt, "endedAt");
        this.checkStatus = CheckStatus.FAILED;
        this.failureReason = failureReason;
        this.failureDetail = failureDetail;
        this.endedAt = endedAt;
    }

    /**
     * Writes the Employee Decision beside a COMPLETED result (REQ-RPT-032); the status does not
     * change. Allowed only after {@code DecisionRecording} found nothing to refuse
     * (RULE-RPT-011 … RULE-RPT-014).
     *
     * @param employeeDecision    the decision
     * @param decidedBy           the deciding employee, exactly as received
     * @param decidedAt           the recording time (ADR-RPT-009)
     * @param approvalApiExecuted whether the decision was executed through the Approval API
     */
    public void recordDecision(EmployeeDecision employeeDecision,
                               String decidedBy,
                               OffsetDateTime decidedAt,
                               boolean approvalApiExecuted) {
        Objects.requireNonNull(employeeDecision, "employeeDecision");
        Objects.requireNonNull(decidedBy, "decidedBy");
        Objects.requireNonNull(decidedAt, "decidedAt");
        this.employeeDecision = employeeDecision;
        this.decidedBy = decidedBy;
        this.decidedAt = decidedAt;
        this.approvalApiExecuted = approvalApiExecuted;
    }

    public Long getCheckRunId() {
        return checkRunId;
    }

    public String getServiceCode() {
        return serviceCode;
    }

    public Integer getVersionNumber() {
        return versionNumber;
    }

    public FetchMode getFetchMode() {
        return fetchMode;
    }

    public String getRequestNumber() {
        return requestNumber;
    }

    public String getEmployeeId() {
        return employeeId;
    }

    public CheckStatus getCheckStatus() {
        return checkStatus;
    }

    public OffsetDateTime getStartedAt() {
        return startedAt;
    }

    /** {@code null} until the first mark RUNNING. */
    public OffsetDateTime getRunningSince() {
        return runningSince;
    }

    /** {@code null} unless COMPLETED or FAILED. */
    public OffsetDateTime getEndedAt() {
        return endedAt;
    }

    /** {@code null} unless COMPLETED. */
    public OverallStatus getOverallStatus() {
        return overallStatus;
    }

    /** {@code null} unless COMPLETED. */
    public String getComparisonModel() {
        return comparisonModel;
    }

    /** {@code null} unless FAILED. */
    public CheckFailureReason getFailureReason() {
        return failureReason;
    }

    /** {@code null} unless FAILED. */
    public String getFailureDetail() {
        return failureDetail;
    }

    /** {@code null} until a decision is recorded. */
    public EmployeeDecision getEmployeeDecision() {
        return employeeDecision;
    }

    /** {@code null} until a decision is recorded. */
    public String getDecidedBy() {
        return decidedBy;
    }

    /** {@code null} until a decision is recorded. */
    public OffsetDateTime getDecidedAt() {
        return decidedAt;
    }

    /** {@code null} until a decision is recorded. */
    public Boolean getApprovalApiExecuted() {
        return approvalApiExecuted;
    }

    /** Database-filled; {@code null} on an instance not yet reloaded after its insert. */
    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    /** Database-filled; {@code null} on an instance not yet reloaded after its insert. */
    public OffsetDateTime getUpdatedAt() {
        return updatedAt;
    }
}
