package io.agenticai.rpt.entity;

import io.agenticai.rpt.domain.FindingOutcome;
import io.agenticai.rpt.entity.converter.FindingOutcomeConverter;
import jakarta.persistence.Column;
import jakarta.persistence.Convert;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Lob;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import org.hibernate.annotations.Immutable;

import java.time.OffsetDateTime;
import java.util.Objects;

/**
 * ENT-RPT-002 Finding — one row of {@code RPT_FINDING} per condition of a completed report
 * (ADR-RPT-001, REQ-RPT-008). Kind {@code transactional}: carries the standard
 * {@code createdAt} / {@code updatedAt} fields.
 *
 * <p>Inserted once by {@code completeCheck} and never updated (REQ-RPT-020): no setter, every
 * column {@code updatable = false}, the class is {@link Immutable} and the only way in is
 * {@link #recorded}. Leaves only with its Check Run — {@code FK_RPT_FINDING_RPT_CHECK_RUN}
 * {@code ON DELETE CASCADE} is the database's. The owning Check Run is referenced by its id, as the
 * dbf-matrix names it ({@code ENT-RPT-002.checkRunId}) — not an association. One position per
 * report: {@code UQ_RPT_FINDING_RUN_POS} (REQ-RPT-010), whose leading column also indexes the FK.
 *
 * <p>RULE-RPT-007 (every finding complete, owner layer domain) is decided by
 * {@code SubmittedReport} before this factory is called.
 */
@Entity
@Immutable
@Table(name = "RPT_FINDING",
        uniqueConstraints = {
                @UniqueConstraint(name = "UQ_RPT_FINDING_RUN_POS",
                        columnNames = {"CHECK_RUN_ID", "POSITION"})
        })
public class Finding {

    /** DBF-RPT-021 — identity key, {@code NUMBER(19) GENERATED BY DEFAULT AS IDENTITY}. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "FINDING_ID", nullable = false, updatable = false)
    private Long findingId;

    /** DBF-RPT-022 — order of the finding in the report, from 1 ({@code CHK_RPT_FINDING_POSITION}). */
    @Column(name = "POSITION", nullable = false, updatable = false)
    private Integer position;

    /** DBF-RPT-023 — the condition the finding is about. */
    @Lob
    @Column(name = "CONDITION_TEXT", nullable = false, updatable = false)
    private String conditionText;

    /** DBF-RPT-024 — the outcome through {@link FindingOutcomeConverter}. */
    @Convert(converter = FindingOutcomeConverter.class)
    @Column(name = "FINDING_OUTCOME", length = 30, nullable = false, updatable = false)
    private FindingOutcome findingOutcome;

    /** DBF-RPT-025 — the actual value found (G10), returned as data. */
    @Lob
    @Column(name = "EVIDENCE", nullable = false, updatable = false)
    private String evidence;

    /** DBF-RPT-026 — the note for the employee. */
    @Lob
    @Column(name = "NOTE", nullable = false, updatable = false)
    private String note;

    /** DBF-RPT-027 — the owning Check Run, {@code FK_RPT_FINDING_RPT_CHECK_RUN} (ON DELETE CASCADE). */
    @Column(name = "CHECK_RUN_ID", nullable = false, updatable = false)
    private Long checkRunId;

    /** DBF-RPT-028 — standard field, database-filled ({@code DEFAULT SYSTIMESTAMP}); mapped read-only. */
    @Column(name = "CREATED_AT", nullable = false, insertable = false, updatable = false)
    private OffsetDateTime createdAt;

    /** DBF-RPT-029 — standard field, database-filled; never changed after insert (REQ-RPT-020). */
    @Column(name = "UPDATED_AT", nullable = false, insertable = false, updatable = false)
    private OffsetDateTime updatedAt;

    /** JPA only. */
    protected Finding() {
    }

    private Finding(Long checkRunId, Integer position, String conditionText,
                    FindingOutcome findingOutcome, String evidence, String note) {
        this.checkRunId = checkRunId;
        this.position = position;
        this.conditionText = conditionText;
        this.findingOutcome = findingOutcome;
        this.evidence = evidence;
        this.note = note;
    }

    /**
     * A finding as {@code completeCheck} stores it — this method stores, it does not decide
     * (RULE-RPT-007 is decided before). Values are checked for presence only.
     *
     * @param checkRunId     the owning Check Run id
     * @param position       the order in the report, from 1 (index as received)
     * @param conditionText  the condition
     * @param findingOutcome the outcome
     * @param evidence       the actual value found
     * @param note           the note for the employee
     * @throws IllegalArgumentException when {@code position} is below 1 (API misuse)
     */
    public static Finding recorded(Long checkRunId, int position, String conditionText,
                                   FindingOutcome findingOutcome, String evidence, String note) {
        Objects.requireNonNull(checkRunId, "checkRunId");
        Objects.requireNonNull(conditionText, "conditionText");
        Objects.requireNonNull(findingOutcome, "findingOutcome");
        Objects.requireNonNull(evidence, "evidence");
        Objects.requireNonNull(note, "note");
        if (position < 1) {
            throw new IllegalArgumentException("position must be 1 or more: " + position);
        }
        return new Finding(checkRunId, position, conditionText, findingOutcome, evidence, note);
    }

    public Long getFindingId() {
        return findingId;
    }

    public Integer getPosition() {
        return position;
    }

    public String getConditionText() {
        return conditionText;
    }

    public FindingOutcome getFindingOutcome() {
        return findingOutcome;
    }

    public String getEvidence() {
        return evidence;
    }

    public String getNote() {
        return note;
    }

    public Long getCheckRunId() {
        return checkRunId;
    }

    /** Database-filled; {@code null} on an instance not yet reloaded after its insert. */
    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    /** Database-filled; {@code null} on an instance not yet reloaded after its insert. */
    public OffsetDateTime getUpdatedAt() {
        return updatedAt;
    }
}
