package io.agenticai.rpt.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Lob;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import org.hibernate.annotations.Immutable;

import java.time.OffsetDateTime;
import java.util.Objects;

/**
 * ENT-RPT-004 Unread Query — one row of {@code RPT_UNREAD_QUERY} per service query of a
 * completed report whose data could not be read (ADR-RPT-001, ADR-CHK-014, REQ-RPT-012). Kind
 * {@code transactional}: carries the standard {@code createdAt} / {@code updatedAt} fields. No
 * query rows are held — the query name and why it was not read only.
 *
 * <p>Inserted once by {@code completeCheck} and never updated (REQ-RPT-020): no setter, every
 * column {@code updatable = false}, the class is {@link Immutable} and the only way in is
 * {@link #recorded}. Leaves only with its Check Run ({@code FK_RPT_UNREAD_QUERY_RPT_CHECK_RUN}
 * {@code ON DELETE CASCADE}, the database's). The owning Check Run is referenced by its id, as the
 * dbf-matrix names it — not an association. One position per report:
 * {@code UQ_RPT_UNREAD_QUERY_RUN_POS} (REQ-RPT-010).
 *
 * <p>No rule is specific to this entity: the presence of name and detail is checked with
 * RULE-RPT-007's not-blank guard, and RULE-RPT-005 reads this list — both in
 * {@code SubmittedReport}.
 */
@Entity
@Immutable
@Table(name = "RPT_UNREAD_QUERY",
        uniqueConstraints = {
                @UniqueConstraint(name = "UQ_RPT_UNREAD_QUERY_RUN_POS",
                        columnNames = {"CHECK_RUN_ID", "POSITION"})
        })
public class UnreadQuery {

    /** DBF-RPT-040 — identity key, {@code NUMBER(19) GENERATED BY DEFAULT AS IDENTITY}. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "UNREAD_QUERY_ID", nullable = false, updatable = false)
    private Long unreadQueryId;

    /** DBF-RPT-041 — order in the report, from 1 ({@code CHK_RPT_UNREAD_QUERY_POSITION}). */
    @Column(name = "POSITION", nullable = false, updatable = false)
    private Integer position;

    /** DBF-RPT-042 — the service query name; a value only. */
    @Column(name = "QUERY_NAME", length = 100, nullable = false, updatable = false)
    private String queryName;

    /** DBF-RPT-043 — why its data was not read. */
    @Lob
    @Column(name = "DETAIL", nullable = false, updatable = false)
    private String detail;

    /** DBF-RPT-044 — the owning Check Run, {@code FK_RPT_UNREAD_QUERY_RPT_CHECK_RUN} (ON DELETE CASCADE). */
    @Column(name = "CHECK_RUN_ID", nullable = false, updatable = false)
    private Long checkRunId;

    /** DBF-RPT-045 — standard field, database-filled ({@code DEFAULT SYSTIMESTAMP}); mapped read-only. */
    @Column(name = "CREATED_AT", nullable = false, insertable = false, updatable = false)
    private OffsetDateTime createdAt;

    /** DBF-RPT-046 — standard field, database-filled; never changed after insert (REQ-RPT-020). */
    @Column(name = "UPDATED_AT", nullable = false, insertable = false, updatable = false)
    private OffsetDateTime updatedAt;

    /** JPA only. */
    protected UnreadQuery() {
    }

    private UnreadQuery(Long checkRunId, Integer position, String queryName, String detail) {
        this.checkRunId = checkRunId;
        this.position = position;
        this.queryName = queryName;
        this.detail = detail;
    }

    /**
     * An unread query as {@code completeCheck} stores it — this method stores, it does not decide.
     *
     * @param checkRunId the owning Check Run id
     * @param position   the order in the report, from 1 (index as received)
     * @param queryName  the service query name
     * @param detail     why its data was not read
     * @throws IllegalArgumentException when {@code position} is below 1 (API misuse)
     */
    public static UnreadQuery recorded(Long checkRunId, int position, String queryName, String detail) {
        Objects.requireNonNull(checkRunId, "checkRunId");
        Objects.requireNonNull(queryName, "queryName");
        Objects.requireNonNull(detail, "detail");
        if (position < 1) {
            throw new IllegalArgumentException("position must be 1 or more: " + position);
        }
        return new UnreadQuery(checkRunId, position, queryName, detail);
    }

    public Long getUnreadQueryId() {
        return unreadQueryId;
    }

    public Integer getPosition() {
        return position;
    }

    public String getQueryName() {
        return queryName;
    }

    public String getDetail() {
        return detail;
    }

    public Long getCheckRunId() {
        return checkRunId;
    }

    /** Database-filled; {@code null} on an instance not yet reloaded after its insert. */
    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    /** Database-filled; {@code null} on an instance not yet reloaded after its insert. */
    public OffsetDateTime getUpdatedAt() {
        return updatedAt;
    }
}
