-- DOC v1 — oracle19c — copy-and-run against a clean schema
-- BLOCK 1 SEQUENCES: none — every PK uses the identity clause

-- BLOCK 2 PARENT TABLES
CREATE TABLE DOC_UPLOADED_DOC (
    UPLOADED_DOCUMENT_ID NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CHECK_ID NUMBER(19) NOT NULL,
    SERVICE_CODE VARCHAR2(100 CHAR) NOT NULL,
    VERSION_NUMBER NUMBER(10,0) NOT NULL,
    DOCUMENT_TYPE VARCHAR2(100 CHAR) NOT NULL,
    FILE_NAME VARCHAR2(255 CHAR) NOT NULL,
    FILE_SIZE NUMBER(19,0) NOT NULL,
    CONTENT BLOB,
    OVERSIZED NUMBER(1) DEFAULT 0 NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE DOC_ENDED_CHECK (
    ENDED_CHECK_ID NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CHECK_ID NUMBER(19) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

-- BLOCK 3 CHILD TABLES: none — DOC has no intra-module FK (DOC_UPLOADED_DOC and DOC_ENDED_CHECK share CHECK_ID as a value)

-- BLOCK 4 COMMENTS
COMMENT ON TABLE DOC_UPLOADED_DOC IS 'ENT-DOC-001 Uploaded Document — one row per file uploaded for one Check in manual fetch mode; hard-deleted when the Check ends (ADR-DOC-008)';
COMMENT ON COLUMN DOC_UPLOADED_DOC.UPLOADED_DOCUMENT_ID IS 'DBF-DOC-001 ENT-DOC-001.uploadedDocumentId — Identifier (identity)';
COMMENT ON COLUMN DOC_UPLOADED_DOC.CHECK_ID IS 'DBF-DOC-002 ENT-DOC-001.checkId — Check identifier as a value from INT; no FK, DOC never reads RPT (ADR-DOC-003)';
COMMENT ON COLUMN DOC_UPLOADED_DOC.SERVICE_CODE IS 'DBF-DOC-003 ENT-DOC-001.serviceCode — Service code of the Check, value of SERVICE_CODE (REG); no FK';
COMMENT ON COLUMN DOC_UPLOADED_DOC.VERSION_NUMBER IS 'DBF-DOC-004 ENT-DOC-001.versionNumber — Service package version of the Check; no FK';
COMMENT ON COLUMN DOC_UPLOADED_DOC.DOCUMENT_TYPE IS 'DBF-DOC-005 ENT-DOC-001.documentType — Document type given by the employee (DOCUMENT_TYPE, REG); one of the version required types (RULE-DOC-002)';
COMMENT ON COLUMN DOC_UPLOADED_DOC.FILE_NAME IS 'DBF-DOC-006 ENT-DOC-001.fileName — File name as uploaded';
COMMENT ON COLUMN DOC_UPLOADED_DOC.FILE_SIZE IS 'DBF-DOC-007 ENT-DOC-001.fileSize — Bytes of the uploaded file; greater than 0 (RULE-DOC-003)';
COMMENT ON COLUMN DOC_UPLOADED_DOC.CONTENT IS 'DBF-DOC-008 ENT-DOC-001.content — The uploaded file; NULL exactly when oversized (RULE-DOC-005)';
COMMENT ON COLUMN DOC_UPLOADED_DOC.OVERSIZED IS 'DBF-DOC-009 ENT-DOC-001.oversized — 1 = larger than the maximum file size, content not kept';
COMMENT ON COLUMN DOC_UPLOADED_DOC.CREATED_AT IS 'DBF-DOC-010 ENT-DOC-001.createdAt — Upload time; filled by the platform';
COMMENT ON COLUMN DOC_UPLOADED_DOC.UPDATED_AT IS 'DBF-DOC-011 ENT-DOC-001.updatedAt — Filled by the platform; equals CREATED_AT (rows are never changed, RULE-DOC-004)';
COMMENT ON TABLE DOC_ENDED_CHECK IS 'ENT-DOC-002 Ended Check — one row per Check whose end CHK reported; refuses a late upload (RULE-DOC-009) and drives the sweep of late uploads (ADR-DOC-015)';
COMMENT ON COLUMN DOC_ENDED_CHECK.ENDED_CHECK_ID IS 'DBF-DOC-012 ENT-DOC-002.endedCheckId — Identifier (identity)';
COMMENT ON COLUMN DOC_ENDED_CHECK.CHECK_ID IS 'DBF-DOC-013 ENT-DOC-002.checkId — Check identifier as a value from CHK; unique; no FK, DOC never reads RPT (ADR-DOC-003)';
COMMENT ON COLUMN DOC_ENDED_CHECK.CREATED_AT IS 'DBF-DOC-014 ENT-DOC-002.createdAt — Time the end of the Check was reported; filled by the platform';
COMMENT ON COLUMN DOC_ENDED_CHECK.UPDATED_AT IS 'DBF-DOC-015 ENT-DOC-002.updatedAt — Filled by the platform; equals CREATED_AT (rows are never changed)';

-- BLOCK 5a PRIMARY KEYS
ALTER TABLE DOC_UPLOADED_DOC ADD CONSTRAINT PK_DOC_UPLOADED_DOC PRIMARY KEY (UPLOADED_DOCUMENT_ID);
ALTER TABLE DOC_ENDED_CHECK ADD CONSTRAINT PK_DOC_ENDED_CHECK PRIMARY KEY (ENDED_CHECK_ID);

-- BLOCK 5b UNIQUE — DOC_UPLOADED_DOC has none: several uploads of one document type per Check are allowed (ADR-DOC-006)
ALTER TABLE DOC_ENDED_CHECK ADD CONSTRAINT UQ_DOC_ENDED_CHECK_CHECK_ID UNIQUE (CHECK_ID);  -- REQ-DOC-060: one row per ended Check; also serves RULE-DOC-009 lookups

-- BLOCK 5c CHECK
ALTER TABLE DOC_UPLOADED_DOC ADD CONSTRAINT CHK_DOC_UPLOADED_DOC_FILE_SIZE CHECK (FILE_SIZE > 0);  -- RULE-DOC-003
ALTER TABLE DOC_UPLOADED_DOC ADD CONSTRAINT CHK_DOC_UPLOADED_DOC_OVERSIZED CHECK (OVERSIZED IN (0, 1));
ALTER TABLE DOC_UPLOADED_DOC ADD CONSTRAINT CHK_DOC_UPLOADED_DOC_CONTENT CHECK ((OVERSIZED = 1 AND CONTENT IS NULL) OR (OVERSIZED = 0 AND CONTENT IS NOT NULL));  -- RULE-DOC-005
ALTER TABLE DOC_UPLOADED_DOC ADD CONSTRAINT CHK_DOC_UPLOADED_DOC_VERSION_NUMBER CHECK (VERSION_NUMBER >= 1);

-- BLOCK 5d INTRA-MODULE FOREIGN KEYS: none

-- XM-DOC-001 SOFT-READ — the document fetch reads ENT-REG-002.fetchMode and the document source settings
-- of the Check's version from REG through the in-process REG interface (CON-REG-009), without an FK.
-- Rationale: REQ-DOC-002, RULE-DOC-001 (data source ENT-DOC-001.serviceCode, ENT-DOC-001.versionNumber, ENT-REG-002.fetchMode).
-- Risk: changes to ENT-REG-002 require impact assessment on REQ-DOC-001 … REQ-DOC-020.
-- XM-DOC-002 SOFT-READ — the document fetch reads ENT-REG-003.sqlText and ENT-REG-003.connectionName of the
-- document source query through the REG interface, without an FK. Rationale: REQ-DOC-004, REQ-DOC-012, REQ-DOC-051,
-- RULE-DOC-006, RULE-DOC-007. Risk: changes to ENT-REG-003 require impact assessment on REQ-DOC-004, REQ-DOC-012, REQ-DOC-051.
-- XM-DOC-003 SOFT-READ — the upload handover and the document fetch read ENT-REG-004.documentType of the version
-- through the REG interface, without an FK. Rationale: RULE-DOC-002 (data source ENT-DOC-001.documentType,
-- ENT-REG-004.documentType), REQ-DOC-035. Risk: changes to ENT-REG-004 require impact assessment on REQ-DOC-021, REQ-DOC-035.
-- XM-DOC-004 SOFT-READ — the document fetch reads ENT-REG-005.connectionType and ENT-REG-005.readOnly by connection
-- name through the REG interface (CON-REG-011), without an FK. Rationale: RULE-DOC-006 (data source ENT-REG-002.fetchMode,
-- ENT-REG-003.connectionName, ENT-REG-005.connectionType), RULE-DOC-007 (data source ENT-REG-003.connectionName,
-- ENT-REG-005.readOnly). Risk: changes to ENT-REG-005 require impact assessment on REQ-DOC-012, REQ-DOC-014, REQ-DOC-052.

-- BLOCK 6 TRIGGERS: none — no SRS rule requires one; audit fields are filled by the platform

-- BLOCK 7 INDEXES (non-PK)
CREATE INDEX IDX_DOC_UPLOADED_DOC_CHECK_ID ON DOC_UPLOADED_DOC (CHECK_ID);
--   DOC_ENDED_CHECK.CHECK_ID is indexed by UQ_DOC_ENDED_CHECK_CHECK_ID (RULE-DOC-009 lookup, REQ-DOC-062 sweep semi-join)

-- BLOCK 8 LOOKUP SEED DATA: none
--   DOC owns FETCH_MODE, DOCUMENT_READ_STATUS and UNREADABLE_REASON: closed enums of the service code that back no
--   DOC column; FETCH_MODE is enforced by CHK_REG_SVC_PKG_VER_FETCH_MODE in REG's script, the other two by the
--   CHECK constraints of the RPT columns that store them (ADR-DOC-010). No lookup table exists in the platform (ADR-REG-010).
--   Consumed open keys DOCUMENT_TYPE and SERVICE_CODE are REG data, entered by loading the pilot package (ADR-REG-010).

-- BLOCK 9 VIEWS: none
-- BLOCK 10 FUNCTIONS / PROCEDURES: none
