-- CHK v1 — oracle19c — copy-and-run against a clean schema
-- BLOCK 1 SEQUENCES: none — every PK uses the identity clause

-- BLOCK 2 PARENT TABLES
CREATE TABLE CHK_ACTIVE_CHECK (
    ACTIVE_CHECK_ID NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CHECK_ID NUMBER(19) NOT NULL,
    CHECK_STATUS VARCHAR2(30 CHAR) NOT NULL,
    DEADLINE_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

-- BLOCK 3 CHILD TABLES: none — CHK has one table and no intra-module FK

-- BLOCK 4 COMMENTS
COMMENT ON TABLE CHK_ACTIVE_CHECK IS 'ENT-CHK-001 Active Check: one row per unfinished Check (status and deadline), hard-deleted when the Check ends (ADR-CHK-015)';
COMMENT ON COLUMN CHK_ACTIVE_CHECK.ACTIVE_CHECK_ID IS 'DBF-CHK-001 system key (identity)';
COMMENT ON COLUMN CHK_ACTIVE_CHECK.CHECK_ID IS 'DBF-CHK-002 the Check identifier returned by the result port (RPT); value only, no FK; one row per Check (RULE-CHK-008)';
COMMENT ON COLUMN CHK_ACTIVE_CHECK.CHECK_STATUS IS 'DBF-CHK-003 CHECK_STATUS code, AWAITING_DOCUMENTS or RUNNING only (RULE-CHK-009)';
COMMENT ON COLUMN CHK_ACTIVE_CHECK.DEADLINE_AT IS 'DBF-CHK-004 end of the upload window (AWAITING_DOCUMENTS) or of the Check timeout (RUNNING)';
COMMENT ON COLUMN CHK_ACTIVE_CHECK.CREATED_AT IS 'DBF-CHK-005 standard field, filled by the platform';
COMMENT ON COLUMN CHK_ACTIVE_CHECK.UPDATED_AT IS 'DBF-CHK-006 standard field, filled by the platform';

-- BLOCK 5a PRIMARY KEYS
ALTER TABLE CHK_ACTIVE_CHECK ADD CONSTRAINT PK_CHK_ACTIVE_CHECK PRIMARY KEY (ACTIVE_CHECK_ID);

-- BLOCK 5b UNIQUE
ALTER TABLE CHK_ACTIVE_CHECK ADD CONSTRAINT UQ_CHK_ACTIVE_CHECK_CHECK_ID UNIQUE (CHECK_ID);  -- RULE-CHK-008

-- BLOCK 5c CHECK
ALTER TABLE CHK_ACTIVE_CHECK ADD CONSTRAINT CHK_CHK_ACTIVE_CHECK_CHECK_STATUS CHECK (CHECK_STATUS IN ('AWAITING_DOCUMENTS', 'RUNNING'));  -- RULE-CHK-009

-- BLOCK 5d INTRA-MODULE FOREIGN KEYS: none

-- XM-CHK-001 SOFT-READ — the start of a Check reads ENT-REG-001.serviceCode and ENT-REG-001.available
-- from REG through the in-process REG interface (CON-REG-013), without an FK. Rationale: REQ-CHK-005,
-- RULE-CHK-001. Risk: changes to ENT-REG-001 require impact assessment on REQ-CHK-005, REQ-CHK-007.
-- XM-CHK-002 SOFT-READ — the pipeline reads ENT-REG-002.versionNumber, ENT-REG-002.serviceKnowledge,
-- ENT-REG-002.inputName, ENT-REG-002.fetchMode and ENT-REG-002.documentSourceQueryName of the Check's version
-- through the REG interface (CON-REG-007, CON-REG-009), without an FK. Rationale: REQ-CHK-007, REQ-CHK-008,
-- REQ-CHK-034, RULE-CHK-003, RULE-CHK-005, RULE-CHK-006, RULE-CHK-007. Risk: changes to ENT-REG-002 require
-- impact assessment on REQ-CHK-007 … REQ-CHK-015, REQ-CHK-027, REQ-CHK-034, REQ-CHK-056, REQ-CHK-057.
-- XM-CHK-003 SOFT-READ — the pipeline reads ENT-REG-003.queryName, ENT-REG-003.connectionName and
-- ENT-REG-003.sqlText of the version through the REG interface, without an FK. Rationale: REQ-CHK-011,
-- REQ-CHK-012, REQ-CHK-015, RULE-CHK-002, RULE-CHK-003, RULE-CHK-005. Risk: changes to ENT-REG-003 require
-- impact assessment on REQ-CHK-011 … REQ-CHK-016.
-- XM-CHK-004 SOFT-READ — the deterministic checks read ENT-REG-004.documentType of the version through the REG
-- interface, without an FK. Rationale: REQ-CHK-019, RULE-CHK-004. Risk: changes to ENT-REG-004 require impact
-- assessment on REQ-CHK-019 … REQ-CHK-022.
-- XM-CHK-005 SOFT-READ — the pipeline reads ENT-REG-005.connectionType and ENT-REG-005.readOnly by connection
-- name through the REG interface (CON-REG-011), without an FK. Rationale: REQ-CHK-013, REQ-CHK-014,
-- RULE-CHK-002. Risk: changes to ENT-REG-005 require impact assessment on REQ-CHK-006, REQ-CHK-013, REQ-CHK-014.

-- BLOCK 6 TRIGGERS: none — no SRS rule requires one; audit fields are filled by the platform

-- BLOCK 7 INDEXES (non-PK)
CREATE INDEX IDX_CHK_ACTIVE_CHECK_DEADLINE_AT ON CHK_ACTIVE_CHECK (DEADLINE_AT);

-- BLOCK 8 LOOKUP SEED DATA: none
--   CHK owns OVERALL_STATUS, CHECK_STATUS, FINDING_OUTCOME and CHECK_FAILURE_REASON: closed enums of the service code.
--   CHECK_STATUS is enforced on CHK_ACTIVE_CHECK.CHECK_STATUS by CHK_CHK_ACTIVE_CHECK_CHECK_STATUS (two values);
--   all four are enforced by the CHECK constraints of the RPT columns that store them through the Check result
--   port (ADR-CHK-016). No lookup table exists in the platform (ADR-REG-010).
--   Consumed keys SERVICE_CODE, DOCUMENT_TYPE, CONNECTION_TYPE are REG data / REG CHECKs; FETCH_MODE,
--   DOCUMENT_READ_STATUS, UNREADABLE_REASON are DOC's enums (ADR-DOC-010).

-- BLOCK 9 VIEWS: none
-- BLOCK 10 FUNCTIONS / PROCEDURES: none
