package io.agenticai.chk.contract;

import java.time.OffsetDateTime;
import java.util.List;
import java.util.Optional;

/**
 * The Check result port — declared by CHK, implemented by RPT (ADR-REG-002, ADR-CHK-011;
 * CON-CHK-006 … CON-CHK-011). CHK owns no report entity and keeps no report storage of its own
 * (REQ-CHK-046): every Check run, result, finding and Check Document row is RPT's, written through
 * this port; CHK never reads RPT's tables.
 *
 * <p><b>Placement.</b> The port lives in {@code chk.contract}, CHK's only importable package, so
 * that RPT implements it without importing a CHK internal: every argument and answer is a value of
 * this package or of the JDK, and every closed lookup travels as its code (CHECK_STATUS,
 * OVERALL_STATUS, FINDING_OUTCOME, CHECK_FAILURE_REASON — CON-CHK-001 … CON-CHK-003), as RPT stores
 * it. No implementation exists in CHK; RPT's version provides the bean.
 *
 * <p>CHK calls the write operations inside its own short READ_WRITE transactions (start, upload
 * confirmation, ending), so an implementation on the same datasource joins them.
 */
public interface CheckResultPort {

    /**
     * CON-CHK-006 — creates the Check run, called once per started Check before its pipeline runs
     * (REQ-CHK-001, REQ-CHK-007).
     *
     * @param serviceCode   the service code
     * @param versionNumber the service package version the Check pinned
     * @param fetchMode     the version's fetch mode code ({@code path}, {@code blob}, {@code manual})
     * @param requestNumber the request number exactly as received (REQ-CHK-002)
     * @param employeeId    the employee identity exactly as received (REQ-CHK-002)
     * @param status        {@code RUNNING} or {@code AWAITING_DOCUMENTS} (CON-CHK-001)
     * @param startedAt     the start time
     * @return the new Check identifier ({@code NUMBER(19)}, generated by RPT); an RPT failure
     *         (not stored) is thrown, and CHK then refuses the start
     */
    Long createCheckRun(String serviceCode,
                        int versionNumber,
                        String fetchMode,
                        String requestNumber,
                        String employeeId,
                        String status,
                        OffsetDateTime startedAt);

    /**
     * CON-CHK-007 — marks the Check RUNNING (REQ-CHK-003, REQ-CHK-057). Errors: not found.
     */
    void markRunning(Long checkId, OffsetDateTime runningSince);

    /**
     * CON-CHK-008 — completes the Check: status COMPLETED with its result (REQ-CHK-044). Carries no
     * document content (REQ-CHK-047) and no Employee Decision (REQ-CHK-033). A failure (not
     * stored) is thrown; CHK then fails the Check with INTERNAL_ERROR (REQ-CHK-048).
     *
     * @param overallStatus    the OVERALL_STATUS code (CON-CHK-001)
     * @param findings         one per condition and per required document type (REQ-CHK-038)
     * @param documentOutcomes the document outcomes, without content
     * @param unreadQueries    the service queries whose data was not read
     * @param metadata         the report metadata (REQ-CHK-045)
     */
    void completeCheck(Long checkId,
                       String overallStatus,
                       List<ReportFinding> findings,
                       List<ReportDocumentOutcome> documentOutcomes,
                       List<ReportUnreadQuery> unreadQueries,
                       ReportMetadata metadata);

    /**
     * CON-CHK-009 — fails the Check: status FAILED, exactly one reason, no Overall Status and no
     * findings (REQ-CHK-054). Errors: not found.
     *
     * @param failureReason the CHECK_FAILURE_REASON code (CON-CHK-003)
     * @param detail        the detail text
     * @param endedAt       the end time
     */
    void failCheck(Long checkId, String failureReason, String detail, OffsetDateTime endedAt);

    /**
     * CON-CHK-010 — reads one Check (REQ-CHK-057 … REQ-CHK-059). The contract's "not found" is an
     * empty answer.
     */
    Optional<CheckRun> getCheck(Long checkId);

    /**
     * CON-CHK-011 — the Checks whose status is AWAITING_DOCUMENTS or RUNNING (REQ-CHK-055); an
     * empty list when there is none.
     */
    List<UnfinishedCheck> listUnfinishedChecks();
}
